window.KHAEMENES_MATH_READINESS_BANK = [
  {id:"a1",tier:1,domain:"arithmetic",prompt:"48 ÷ 6 = ?",choices:["8","6","7","9"],answer:0},
  {id:"a2",tier:1,domain:"arithmetic",prompt:"Which value is greatest?",choices:["0.7","0.07","0.17","0.27"],answer:0},
  {id:"f1",tier:1,domain:"fractions",prompt:"3/4 + 1/4 = ?",choices:["1","4/8","3/8","2"],answer:0},
  {id:"f2",tier:1,domain:"fractions",prompt:"0.25 is equivalent to...",choices:["1/4","1/2","1/5","25/10"],answer:0},
  {id:"i1",tier:1,domain:"integers",prompt:"-6 + 10 = ?",choices:["4","-4","16","-16"],answer:0},
  {id:"i2",tier:1,domain:"integers",prompt:"|-12| = ?",choices:["12","-12","0","1/12"],answer:0},
  {id:"r1",tier:1,domain:"ratio",prompt:"If 3 notebooks cost $9, one notebook costs...",choices:["$3","$6","$9","$27"],answer:0},
  {id:"r2",tier:1,domain:"ratio",prompt:"Which ratio is equivalent to 2:5?",choices:["6:15","4:15","10:2","5:2"],answer:0},

  {id:"e1",tier:2,domain:"expressions",prompt:"Simplify 3x + 2x.",choices:["5x","6x","5x²","x"],answer:0},
  {id:"e2",tier:2,domain:"expressions",prompt:"If x = 4, then 2x + 3 = ?",choices:["11","8","9","14"],answer:0},
  {id:"q1",tier:2,domain:"equations",prompt:"Solve x + 7 = 12.",choices:["5","19","-5","84"],answer:0},
  {id:"q2",tier:2,domain:"equations",prompt:"Solve 3x = 21.",choices:["7","18","63","24"],answer:0},
  {id:"c1",tier:2,domain:"coordinates",prompt:"In the point (4,-3), the x-coordinate is...",choices:["4","-3","1","7"],answer:0},
  {id:"c2",tier:2,domain:"coordinates",prompt:"Which point lies on the y-axis?",choices:["(0,5)","(5,0)","(2,3)","(-1,4)"],answer:0},
  {id:"l1",tier:2,domain:"linear",prompt:"Slope describes...",choices:["rate of change","area","angle sum","probability"],answer:0},
  {id:"l2",tier:2,domain:"linear",prompt:"For y = 2x + 1, what is y when x = 3?",choices:["7","6","5","9"],answer:0},

  {id:"m1",tier:3,domain:"measurement",prompt:"Area of a rectangle with length 8 and width 5 is...",choices:["40","26","13","80"],answer:0},
  {id:"m2",tier:3,domain:"measurement",prompt:"A right triangle has legs 3 and 4. Its hypotenuse is...",choices:["5","6","7","12"],answer:0},
  {id:"g1",tier:3,domain:"angles",prompt:"Supplementary angles sum to...",choices:["180°","90°","360°","45°"],answer:0},
  {id:"g2",tier:3,domain:"angles",prompt:"Vertical angles are...",choices:["congruent","always supplementary","always acute","unrelated"],answer:0},
  {id:"s1",tier:3,domain:"systems",prompt:"If x+y=10 and x=4, then y=...",choices:["6","14","4","10"],answer:0},
  {id:"s2",tier:3,domain:"systems",prompt:"A solution to a system of two linear equations is the point where their graphs...",choices:["intersect","start","become parallel","cross the x-axis"],answer:0},
  {id:"x1",tier:3,domain:"exponents",prompt:"2³ · 2² = ?",choices:["2⁵","4⁵","2⁶","4³"],answer:0},
  {id:"x2",tier:3,domain:"exponents",prompt:"x⁵ ÷ x² = ?",choices:["x³","x⁷","x²","3x"],answer:0},

  {id:"fa1",tier:4,domain:"factoring",prompt:"Factor x² + 5x + 6.",choices:["(x+2)(x+3)","(x+1)(x+6)","(x-2)(x-3)","x(x+5)+6"],answer:0},
  {id:"fa2",tier:4,domain:"factoring",prompt:"Which expression has a greatest common factor of 3x?",choices:["6x²+9x","6x+9","3x²+5x","9x²+4"],answer:0},
  {id:"qu1",tier:4,domain:"quadratics",prompt:"The graph of y=x² is a...",choices:["parabola","line","circle","hyperbola"],answer:0},
  {id:"qu2",tier:4,domain:"quadratics",prompt:"Solve x²=49.",choices:["x=±7","x=7 only","x=49","x=±49"],answer:0},
  {id:"fn1",tier:4,domain:"functions",prompt:"If f(x)=3x-2, then f(4)=...",choices:["10","12","14","6"],answer:0},
  {id:"fn2",tier:4,domain:"functions",prompt:"A function assigns each input...",choices:["exactly one output","two outputs","no outputs","only positive outputs"],answer:0},
  {id:"p1",tier:4,domain:"polynomials",prompt:"(x+2)(x+3) expands to...",choices:["x²+5x+6","x²+6x+5","x²+5","x²+6"],answer:0},
  {id:"p2",tier:4,domain:"polynomials",prompt:"The degree of 4x³-2x+7 is...",choices:["3","4","2","7"],answer:0},

  {id:"ra1",tier:5,domain:"rational",prompt:"For x≠0, x²/x simplifies to...",choices:["x","x²","1/x","2x"],answer:0},
  {id:"ra2",tier:5,domain:"rational",prompt:"Which value is excluded from 1/(x-4)?",choices:["4","0","1","-4"],answer:0},
  {id:"el1",tier:5,domain:"exponential-log",prompt:"If 2ˣ=8, then x=...",choices:["3","4","2","8"],answer:0},
  {id:"el2",tier:5,domain:"exponential-log",prompt:"log₁₀(100)=...",choices:["2","10","100","1"],answer:0},
  {id:"rt1",tier:5,domain:"right-triangle",prompt:"In a right triangle, sin θ equals...",choices:["opposite/hypotenuse","adjacent/hypotenuse","opposite/adjacent","hypotenuse/opposite"],answer:0},
  {id:"rt2",tier:5,domain:"right-triangle",prompt:"For a 30-60-90 triangle, the side opposite 30° is...",choices:["half the hypotenuse","equal to the hypotenuse","twice the hypotenuse","unrelated"],answer:0},
  {id:"tr1",tier:5,domain:"trigonometry",prompt:"sin²θ + cos²θ = ...",choices:["1","0","2","tan θ"],answer:0},
  {id:"tr2",tier:5,domain:"trigonometry",prompt:"tan θ = ...",choices:["sin θ / cos θ","cos θ / sin θ","1/sin θ","1/cos θ"],answer:0},

  {id:"ci1",tier:6,domain:"composition-inverse",prompt:"If f(x)=x+3 and g(x)=2x, then f(g(2))=...",choices:["7","10","8","5"],answer:0},
  {id:"ci2",tier:6,domain:"composition-inverse",prompt:"If f(x)=x-5, then f⁻¹(x)=...",choices:["x+5","x-5","5-x","1/(x-5)"],answer:0},
  {id:"lr1",tier:6,domain:"limit-readiness",prompt:"As x approaches 2, the values of x+3 approach...",choices:["5","3","2","infinity"],answer:0},
  {id:"lr2",tier:6,domain:"limit-readiness",prompt:"Which idea best describes a limit?",choices:["the value a function approaches","the largest x-value","the slope only","an equation with no variables"],answer:0}
];
