(()=>{
"use strict";
const FORMAL_STORE="khaemenes_science9_midterm_by_learner_v1",PREVIEW_STORE="khaemenes_science9_midterm_preview_v1",PASS=80,$=id=>document.getElementById(id);
const ctx=window.KhaemenesHighContinuity?.getSummary?.()||{eligible:false,learner:null};
const formal=Boolean(ctx.eligible&&ctx.learner?.grade==="grade-09"),learnerId=formal?ctx.learner.learnerId:null,nickname=formal?(ctx.learner.nickname||"Grade 09 Scholar"):"Preview Scholar";
const q=(domain,prompt,correct,wrongs,explain)=>({domain,prompt,correct,wrongs,explain});
const RAW=[
q("Safety","What should happen before materials are handled in a supervised investigation?","Review hazards, controls, disposal, and stop conditions",["Begin the procedure immediately","Assume familiar materials are safe","Wait until a problem occurs to discuss safety"],"Safe investigations identify hazards and controls before work begins."),
q("Safety","What is the safest response to an unlabeled substance?","Do not use it; notify the supervising adult",["Smell it","Taste a tiny amount","Mix it with water"],"Unknown substances are not used until identity and handling are resolved."),
q("Inquiry","Which feature makes a scientific question testable?","It can be investigated with observable or measurable evidence",["It guarantees one preferred conclusion","It can only be answered by opinion","It avoids defining variables"],"Testable questions connect to evidence that can be observed or measured."),
q("Inquiry","In an experiment testing fertilizer amount on plant growth, the independent variable is…","fertilizer amount",["plant growth","final height measurement","the conclusion"],"The independent variable is deliberately changed."),
q("Inquiry","Why are repeated trials useful?","They help reveal variability and reduce the influence of random chance",["They guarantee the hypothesis is correct","They eliminate all measurement error","They make controls unnecessary"],"Repeated trials improve reliability but do not remove all uncertainty."),
q("Inquiry","Why are controlled variables held as constant as practical?","To make the effect of the independent variable easier to interpret",["To force identical outcomes","To eliminate every uncertainty","To avoid measuring the dependent variable"],"Controls reduce competing explanations."),
q("Data","A temperature rises from 20°C to 30°C in 5 minutes. What is the average rate of change?","2°C/min",["1°C/min","5°C/min","10°C/min"],"Rate = change in temperature divided by time: 10/5 = 2."),
q("Data","A graph starts its y-axis at 95 rather than 0. Why should a reader notice?","It may visually exaggerate small differences",["It makes all data false","It proves causation","Axes never affect interpretation"],"Truncated axes can change visual impression without changing the underlying values."),
q("Data","If two variables are correlated, what can be concluded immediately?","They vary together in the observed data, but causation needs more evidence",["One definitely causes the other","The data are invalid","No relationship exists"],"Correlation alone does not establish causation."),
q("Cells","Which organelle contains most eukaryotic genetic material?","nucleus",["ribosome","cell membrane","Golgi apparatus"],"Most eukaryotic DNA is housed in the nucleus."),
q("Cells","What does selectively permeable mean?","Some substances cross a membrane more readily than others",["Nothing can cross","Everything crosses at the same rate","Only water can ever cross"],"Selective permeability means passage differs among substances."),
q("Cells","Osmosis is specifically the net movement of…","water across a selectively permeable membrane",["DNA between cells","electrons through a wire","proteins through any solid wall"],"Osmosis concerns water movement across a selectively permeable membrane."),
q("Cells","Diffusion tends to produce net movement from…","higher concentration toward lower concentration",["lower concentration toward higher concentration without energy","the nucleus toward every membrane","cold regions toward warm regions only"],"Net diffusion follows a concentration gradient."),
q("Energy","Which process transfers chemical energy from glucose into forms cells can use?","cellular respiration",["osmosis","mitosis","transcription alone"],"Cellular respiration transfers energy from fuel molecules into usable cellular forms."),
q("Energy","Where does the carbon in plant glucose primarily come from?","carbon dioxide",["sunlight","soil minerals only","oxygen gas"],"Photosynthesis incorporates carbon from carbon dioxide into organic molecules."),
q("Energy","Which statement best connects photosynthesis and respiration?","Matter cycles between products and reactants while energy is transformed",["They are identical processes","Both create matter from nothing","Neither involves chemical reactions"],"The processes are linked through matter while energy changes form."),
q("Genetics","In a heterozygous Aa parent, what fraction of gametes is expected to carry allele a?","50%",["0%","25%","100%"],"Alleles separate during gamete formation, producing A and a in equal expected proportions."),
q("Genetics","What is a genotype?","An organism's allele combination for a trait or locus",["Only the visible trait","Any environmental influence","A chromosome count only"],"Genotype refers to genetic constitution; phenotype refers to observable traits."),
q("Genetics","Why are Punnett squares probability models rather than guarantees?","Each offspring event is probabilistic and small samples can differ from expected ratios",["Genes do not influence inheritance","Every family must match the exact ratio","Punnett squares change alleles"],"Expected probabilities need not appear exactly in small samples."),
q("Ecology","What is the primary role of producers in most ecosystems?","Convert external energy into chemical energy stored in organic matter",["Consume all decomposers","Create matter from nothing","Prevent nutrient cycling"],"Producers capture energy and build organic matter."),
q("Ecology","Why are decomposers important?","They break down organic material and return nutrients to usable pools",["They stop all energy loss","They replace producers","They create new elements"],"Decomposition returns matter to nutrient cycles."),
q("Ecology","Why does available energy generally decrease at higher trophic levels?","Organisms use and dissipate much of the energy they obtain",["Energy is destroyed by consumers","Producers contain no energy","Predators cannot metabolize food"],"Energy transfer is inefficient because organisms use energy and release much as heat."),
q("Ecology","A population exceeds the resources its environment can sustain. Which idea is most relevant?","carrying capacity",["atomic number","diffusion","electronegativity"],"Carrying capacity describes the population size an environment can sustain over time."),
q("Evolution","Which statement best distinguishes adaptation from an individual's short-term response?","An adaptation is a heritable population-level trait shaped across generations",["Any learned behavior is an adaptation","Every adaptation appears because an organism needs it","Adaptation happens within one individual during a single day"],"Evolutionary adaptations are heritable and population-level across generations."),
q("Evolution","Why can variation within a population matter for natural selection?","Different heritable traits can affect survival or reproduction under particular conditions",["Variation guarantees every organism survives","Variation makes environments irrelevant","Only acquired traits are inherited"],"Selection acts on heritable variation when traits affect reproductive success."),
q("Matter","Which statement best reflects conservation of matter in an ordinary chemical reaction?","The number of atoms of each element is conserved",["Atoms disappear when bonds break","Mass always increases","Products contain no reactant atoms"],"Chemical reactions rearrange atoms rather than create or destroy them."),
q("Atoms","What does atomic number identify?","the number of protons in the nucleus",["the number of neutrons only","mass in grams","the number of electron shells"],"An element is defined by its proton number."),
q("Atoms","Elements in the same period occupy the same…","horizontal row",["vertical group","isotope","compound family"],"Periods are horizontal rows; groups are vertical columns."),
q("Atoms","Why can periodic-table position help predict properties?","Electron structure changes in recurring patterns across the table",["Every element in a row is identical","Atomic masses are all equal","Position determines temperature"],"Recurring electron-configuration patterns underlie periodic trends."),
q("Bonding","Which description best matches an ionic bonding model?","Attraction between oppositely charged ions after electron transfer",["Shared electron pairs only","Gravitational attraction","A change in the atomic nucleus"],"Ionic bonds are modeled as electrostatic attraction between oppositely charged ions."),
q("Bonding","Covalent bonding is modeled primarily as…","sharing electron pairs between atoms",["complete proton transfer","gravitational attraction","loss of all valence electrons by both atoms"],"Covalent bonds involve shared electron density."),
q("Bonding","Why do bonding models focus on valence electrons?","Valence electrons are most directly involved in ordinary chemical interactions",["Core protons move between atoms","Neutrons form molecular bonds","Valence electrons determine isotope mass"],"Chemical bonding chiefly involves outer electrons."),
q("Reactions","What must be conserved when balancing an ordinary chemical equation?","the number of atoms of each element",["the number of molecules on each side","the physical state of every substance","the temperature"],"Balanced equations represent conservation of atoms."),
q("Reactions","Why do coefficients change when balancing equations but subscripts do not?","Coefficients change amounts; changing subscripts would change substance identities",["Subscripts never represent atoms","Coefficients change element identity","Both can be changed freely"],"Balancing changes relative amounts without changing chemical formulas."),
q("Evidence","A result is unusual, but the measuring instrument was uncalibrated. What should happen next?","Calibrate or check the instrument and replicate before making a strong claim",["Publish immediately","Assume the unusual result is correct","Discard all science"],"Questionable measurement quality calls for instrument checks and replication."),
q("Evidence","A treatment claim is based on three people improving. What is the strongest next question?","Was there a comparison group and a larger, well-designed sample?",["Did they like the treatment?","Was it expensive?","Was the claim popular?"],"Stronger causal evidence requires appropriate design and adequate sampling."),
q("Models","Why does a scientific model sometimes change?","New evidence can reveal limits in the earlier model",["Science ignores evidence","Models are guesses with no evidence","A model must never be revised"],"Models are revised when evidence supports a better representation."),
q("CER","Which response best follows Claim–Evidence–Reasoning?","A clear claim, relevant evidence, and an explanation linking the evidence to the claim",["A claim with no evidence","A list of facts with no conclusion","A conclusion more certain than the data support"],"CER requires an explicit logical connection between claim and evidence."),
q("Sources","Which source-use practice is strongest in science?","Record provenance, methods or evidence, date, attribution, and important limitations",["Use the first result automatically","Accept a source because it agrees with your prediction","Remove uncertainty to sound more confident"],"Scientific source evaluation depends on provenance, methods, evidence, and limitations."),
q("Design","Two groups differ in both temperature and light level. Why is causal interpretation difficult?","The changed variables are confounded",["Temperature never affects results","Light cannot be measured","Controls are unnecessary"],"When multiple variables change together, their individual effects are difficult to separate.")
];
const rotate=(item,i)=>{const base=[item.correct,...item.wrongs],shift=(i*3+1)%4,choices=base.map((_,j)=>base[(j-shift+4)%4]);return {...item,choices,answer:choices.indexOf(item.correct)}};
const BANK=RAW.map(rotate),WRITTEN=[
"Design a fair investigation for a question of your choice. Identify the independent variable, dependent variable, at least two controlled variables, one safety consideration, and the evidence that would count as a useful result.",
"Explain how matter and energy move differently through an ecosystem. Use producers, consumers, decomposers, and energy loss in your explanation.",
"A source claims that two correlated variables prove one causes the other. Explain why that conclusion may be too strong and describe one kind of additional evidence that would improve the causal claim.",
"Choose one cell, genetics, ecology, or chemistry concept from the first semester. Explain it accurately, give one concrete example, and identify one common misconception about it."
];
function read(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch{return f}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
let rec=formal?(read(FORMAL_STORE,{})[learnerId]||{answers:{},written:{},attempts:0}):read(PREVIEW_STORE,{answers:{},written:{},attempts:0});
$("identity").innerHTML=formal?"<strong>"+nickname+" · Formal Grade 09</strong><br>Midterm evidence is learner-scoped. Family Registry remains placement authority.":"<strong>Preview / Practice</strong><br>This attempt does not create formal Science 9 mastery.";
function save(){rec.updatedAt=new Date().toISOString();if(formal){const all=read(FORMAL_STORE,{});all[learnerId]=rec;write(FORMAL_STORE,all)}else write(PREVIEW_STORE,rec)}
function render(){
 $("questions").innerHTML=BANK.map((it,i)=>`<div class="question"><strong>${i+1}. ${it.prompt}</strong><p class="small">${it.domain}</p><div class="choices">${it.choices.map((c,j)=>`<label class="choice"><input type="radio" name="q${i}" value="${j}" ${Number(rec.answers?.[i])===j?"checked":""}><span>${c}</span></label>`).join("")}</div><div class="feedback" id="fb${i}"></div></div>`).join("");
 $("written").innerHTML=WRITTEN.map((p,i)=>`<div class="written"><label for="w${i}"><strong>${i+1}. ${p}</strong></label><textarea id="w${i}"></textarea></div>`).join("");WRITTEN.forEach((_,i)=>{$("w"+i).value=rec.written?.[i]||""});
 document.querySelectorAll('input[type="radio"]').forEach(el=>el.addEventListener("change",()=>{const i=Number(el.name.slice(1));rec.answers[i]=Number(el.value);save();progress()}));
 WRITTEN.forEach((_,i)=>$("w"+i).addEventListener("input",()=>{rec.written[i]=$("w"+i).value}));progress();
}
function progress(){const n=Object.keys(rec.answers||{}).filter(k=>Number.isInteger(Number(rec.answers[k]))).length;$("progressText").textContent=n+" of 40 objective questions answered";$("progressFill").style.width=(n/40*100)+"%"}
function saveWritten(){WRITTEN.forEach((_,i)=>rec.written[i]=$("w"+i).value.trim());save();alert("Written evidence saved.")}
function score(){let correct=0,answered=0;BANK.forEach((it,i)=>{const v=rec.answers?.[i],fb=$("fb"+i);if(!Number.isInteger(Number(v))){fb.textContent="Choose an answer.";fb.className="feedback bad";return}answered++;const ok=Number(v)===it.answer;if(ok)correct++;fb.textContent=(ok?"Correct. ":"Review: ")+it.explain;fb.className="feedback "+(ok?"good":"bad")});if(answered<40){alert("Complete all 40 objective questions before scoring.");return}WRITTEN.forEach((_,i)=>rec.written[i]=$("w"+i).value.trim());const pct=Math.round(correct/40*1000)/10;rec.attempts=Number(rec.attempts||0)+1;rec.objective={score:correct,total:40,percent:pct,passed:pct>=PASS,submittedAt:new Date().toISOString(),attempts:rec.attempts};rec.constructed={submitted:WRITTEN.every((_,i)=>Boolean(rec.written[i])),count:WRITTEN.filter((_,i)=>Boolean(rec.written[i])).length,reviewStatus:"pending-academy-adult-review"};save();const result=$("result");result.hidden=false;result.innerHTML=`<h2>${correct}/40 · ${pct}%</h2><p><strong>${pct>=PASS?"Objective midterm mastery reached.":"Objective midterm mastery not yet reached."}</strong> ${pct>=PASS?"The 80% course threshold is satisfied for the objective section.":"Review the explanations and reassess when ready; Semester II remains locked until objective mastery reaches 80%."}</p><p>Constructed responses saved: ${rec.constructed.count}/4. Written evidence remains pending Academy/adult review and is not auto-scored.</p>`;result.scrollIntoView({behavior:"smooth",block:"center"})}
$("scoreBtn").onclick=score;$("saveBtn").onclick=saveWritten;$("printBtn").onclick=()=>print();$("resetBtn").onclick=()=>{if(!confirm("Reset this midterm attempt? Saved formal evidence from earlier scored attempts is retained only if you cancel this reset."))return;rec={answers:{},written:{},attempts:Number(rec.attempts||0)};save();render();$("result").hidden=true};render();
})();