"use strict";
const SF_QUESTIONS=[
{id:"SF-A01",strand:"Scientific Thinking & Evidence",type:"mc",prompt:"A student writes, ‘The liquid is cloudy, so a new substance definitely formed.’ Which statement is most scientifically defensible?",options:["Cloudiness is an observation; formation of a new substance is an inference requiring more evidence.","Cloudiness proves a chemical reaction occurred.","The statement contains only observations.","The liquid must be a mixture."],answer:0},
{id:"SF-A02",strand:"Scientific Thinking & Evidence",type:"mc",prompt:"Which question is most testable?",options:["Does light help plants?","How does 4, 8, or 12 hours of daily light affect mean seedling height after 14 days under otherwise matched conditions?","Are plants interesting?","Which plant is best?"],answer:1},
{id:"SF-A03",strand:"Scientific Thinking & Evidence",type:"mc",prompt:"Water temperature is changed and dissolving time is measured. Which pairing is correct?",options:["Independent: dissolving time; dependent: temperature","Independent: temperature; dependent: dissolving time","Independent: container; dependent: sugar mass","Independent: timer; dependent: room"],answer:1},
{id:"SF-A04",strand:"Scientific Thinking & Evidence",type:"mc",prompt:"Which choice correctly distinguishes claim, evidence, and reasoning?",options:["Claim = data; evidence = opinion; reasoning = title","Claim answers the question; evidence is relevant data; reasoning explains why the evidence supports the claim using scientific ideas.","Claim and evidence are identical.","Reasoning is only a restatement of the evidence."],answer:1},
{id:"SF-A05",strand:"Scientific Thinking & Evidence",type:"text",prompt:"Two variables rise together in an observational dataset. Explain why that does not by itself establish causation and give one plausible competing explanation.",rubric:"Full credit: states that association/correlation alone does not establish causation AND gives a plausible alternative such as confounding, reverse direction, selection, coincidence, or measurement effects."},
{id:"SF-B01",strand:"Measurement & Quantitative Reasoning",type:"mc",prompt:"Convert 2.75 m to centimeters.",options:["0.0275 cm","27.5 cm","275 cm","2750 cm"],answer:2},
{id:"SF-B02",strand:"Measurement & Quantitative Reasoning",type:"mc",prompt:"A sample has mass 63 g and volume 21 cm³. What is its density?",options:["3 g/cm³","42 g/cm³","84 g/cm³","1323 g/cm³"],answer:0},
{id:"SF-B03",strand:"Measurement & Quantitative Reasoning",type:"mc",prompt:"A temperature rises from 18 °C to 30 °C in 4 minutes. What is the average rate of temperature change?",options:["3 °C/min","4.5 °C/min","12 °C/min","48 °C/min"],answer:0},
{id:"SF-B04",strand:"Measurement & Quantitative Reasoning",type:"mc",prompt:"A measurement rises from 50 to 65. Which pair is correct?",options:["Absolute change 15; percent change 30%","Absolute change 30; percent change 15%","Absolute change 15; percent change 15%","Absolute change 65; percent change 30%"],answer:0},
{id:"SF-B05",strand:"Measurement & Quantitative Reasoning",type:"text",prompt:"A calculator gives 7.3170731707 g/cm³ from measurements recorded only to tenths. Explain why reporting every calculator digit is misleading and propose a defensible way to report the result.",rubric:"Full credit: explains that calculator digits exceed measurement precision/resolution AND proposes rounding/reporting consistent with the measurement quality."},
{id:"SF-C01",strand:"Tables, Graphs & Data",type:"mc",prompt:"For Trial Y values 10 at 0 min and 25 at 6 min, what is the average 0–6 minute rate?",options:["1.5 units/min","2.5 units/min","4.2 units/min","15 units/min"],answer:1},
{id:"SF-C02",strand:"Tables, Graphs & Data",type:"mc",prompt:"Which statement is a direct quantitative observation?",options:["Trial Y increased from 10 to 25 between 0 and 6 minutes.","Trial Y increased because the treatment accelerated a reaction.","The treatment must be better.","The mechanism is proven."],answer:0},
{id:"SF-C03",strand:"Tables, Graphs & Data",type:"mc",prompt:"A graph compares values 98 and 100 but begins the y-axis at 97. What is the best interpretation?",options:["The graph is automatically fraudulent.","The truncated axis can visually magnify a small numerical difference, so the scale and absolute values must be inspected.","All graphs must begin at zero.","Axis scale never affects visual interpretation."],answer:1},
{id:"SF-C04",strand:"Tables, Graphs & Data",type:"mc",prompt:"Two groups have the same mean but one group has much greater spread. Which conclusion is best?",options:["The datasets are equivalent because the means match.","The mean alone is insufficient; variability also matters.","The group with greater spread must be wrong.","Spread never affects interpretation."],answer:1},
{id:"SF-C05",strand:"Tables, Graphs & Data",type:"text",prompt:"A scatterplot shows that hotter days are associated with greater electricity use. Give one direct observation, one competing explanation or confounder, and one additional measurement that would help evaluate the relationship.",rubric:"Full credit: separates observation from explanation, supplies a plausible competing factor such as air-conditioning use/occupancy/time of year, and proposes a relevant additional measurement."},
{id:"SF-D01",strand:"Matter & Energy Foundations",type:"mc",prompt:"Which statement best distinguishes a compound from a mixture?",options:["A compound contains elements chemically combined in defined relationships; a mixture contains substances together without requiring chemical bonding between them.","A mixture is always one element.","A compound can be separated only by filtering.","There is no difference."],answer:0},
{id:"SF-D02",strand:"Matter & Energy Foundations",type:"mc",prompt:"Ice melts in a sealed container. Which statement is correct?",options:["A new substance forms.","Water molecules change identity.","Particle arrangement and motion change while chemical identity remains water.","Mass must decrease."],answer:2},
{id:"SF-D03",strand:"Matter & Energy Foundations",type:"mc",prompt:"A sealed reaction vessel has mass 150.2 g before and 150.2 g after bubbles form. What does this support?",options:["Matter was created as gas.","Within measurement limits, total mass was conserved in the defined closed system.","Gas has no mass.","Energy became matter in ordinary classroom chemistry."],answer:1},
{id:"SF-D04",strand:"Matter & Energy Foundations",type:"mc",prompt:"Why can a warm bathtub contain more total thermal energy than a hotter cup of water?",options:["Temperature and thermal energy are always identical.","Total thermal energy depends on amount and material as well as temperature.","The bathtub must have a higher temperature.","Water in a cup has no thermal energy."],answer:1},
{id:"SF-D05",strand:"Matter & Energy Foundations",type:"text",prompt:"Trace energy through a battery-powered fan and correct the statement ‘the fan uses up the energy until it disappears.’",rubric:"Full credit: identifies transfer from chemical energy in the battery through electrical processes to motion and thermal/sound transfers, and states that energy is transformed/transferred rather than disappearing."},
{id:"SF-E01",strand:"Cells, Scale & Biological Organization",type:"mc",prompt:"Which is a core idea of cell theory?",options:["All living organisms are composed of one or more cells.","Cells arise spontaneously from nonliving matter during normal growth.","Every cell has a cell wall.","All cells are identical."],answer:0},
{id:"SF-E02",strand:"Cells, Scale & Biological Organization",type:"mc",prompt:"Which statement best describes diffusion?",options:["Particles intentionally seek low concentration.","Random molecular motion produces net movement from higher toward lower concentration when a pathway exists.","Particles stop moving at equilibrium.","Diffusion requires a pump in every case."],answer:1},
{id:"SF-E03",strand:"Cells, Scale & Biological Organization",type:"mc",prompt:"At dynamic equilibrium across a membrane, what happens?",options:["All particle motion stops.","Particles continue moving in both directions but there is no net change in distribution.","All particles move to one side.","The membrane disappears."],answer:1},
{id:"SF-E04",strand:"Cells, Scale & Biological Organization",type:"mc",prompt:"For cubes with side lengths 1, 2, and 3 units, SA:V changes 6:1 → 3:1 → 2:1. What is the biological implication?",options:["As size increases, exchange surface grows faster than volume.","As size increases, surface area relative to volume decreases, which can constrain exchange.","SA:V never affects biological exchange.","Larger cells always exchange faster."],answer:1},
{id:"SF-E05",strand:"Cells, Scale & Biological Organization",type:"text",prompt:"Build a functional chain from specialized cell → tissue → organ → organ system → organism and explain one relationship between adjacent levels.",rubric:"Full credit: gives the correct nested order AND explains a functional relationship, not merely a list of names."},
{id:"SF-F01",strand:"Systems, Models & Scientific Literacy",type:"mc",prompt:"Why does system boundary choice matter?",options:["It determines what is treated as inside/outside and which matter or energy transfers cross the boundary.","It changes the laws of nature.","It eliminates uncertainty.","It makes measurements unnecessary."],answer:0},
{id:"SF-F02",strand:"Systems, Models & Scientific Literacy",type:"mc",prompt:"Why is ‘exercise → breathing’ an incomplete causal model?",options:["Arrows never belong in science.","It names a relationship without identifying intermediate mechanisms or measurable state changes.","Exercise and breathing can never be related.","Causal models should contain only one node."],answer:1},
{id:"SF-F03",strand:"Systems, Models & Scientific Literacy",type:"mc",prompt:"What distinguishes feedback from a one-way causal chain?",options:["Feedback contains a later effect that returns to influence an earlier component or variable.","Feedback always has exactly two nodes.","Feedback is any correlation.","Feedback has no direction."],answer:0},
{id:"SF-F04",strand:"Systems, Models & Scientific Literacy",type:"mc",prompt:"Which statement correctly distinguishes S, P, and I in scientific notes?",options:["S = source-supported, P = paraphrase, I = student inference/synthesis.","S = speculation, P = proof, I = irrelevant.","All three mean quotation.","I statements never need evidence."],answer:0},
{id:"SF-F05",strand:"Systems, Models & Scientific Literacy",type:"text",prompt:"A new dataset conflicts with your original scientific model. Describe the scientifically appropriate response, including what should happen to the model and what further evidence may be needed.",rubric:"Full credit: says to preserve/report the conflicting evidence, reassess assumptions/methods, revise or reject parts of the model as warranted, and seek additional discriminating evidence rather than hiding the result."}
];
(() => {
 const KEY="khaemenes_science_foundations_v1",ASSESSMENT_ID="science-foundations-mastery-v1",VERSION="1.0",PASS=24;
 let current=0,answers={};
 const $=(s,p=document)=>p.querySelector(s);
 const objective=SF_QUESTIONS.filter(q=>q.type==="mc"),constructed=SF_QUESTIONS.filter(q=>q.type==="text");
 function readState(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}}
 function writeState(s){localStorage.setItem(KEY,JSON.stringify(s));}
 function escape(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
 function loadDraft(){const s=readState();answers={...(s.draftAnswers||{})};}
 function saveDraft(){const s=readState();s.draftAnswers=answers;s.updatedAt=new Date().toISOString();writeState(s);updateProgress();}
 function answered(q){const v=answers[q.id];return q.type==="mc"?Number.isInteger(v):typeof v==="string"&&v.trim().length>0;}
 function render(){const q=SF_QUESTIONS[current];$("#strandLabel").textContent=q.strand;$("#questionNumber").textContent=`${q.id} · Question ${current+1} of ${SF_QUESTIONS.length}`;$("#questionPrompt").textContent=q.prompt;const box=$("#answerArea");if(q.type==="mc"){box.innerHTML=q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[q.id]===i?'checked':''}><span>${escape(o)}</span></label>`).join("");box.querySelectorAll("input").forEach(el=>el.addEventListener("change",e=>{answers[q.id]=Number(e.target.value);saveDraft();renderNav();}));}else{box.innerHTML=`<label for="constructedResponse" class="eyebrow">Constructed explanation · reviewer scored</label><textarea id="constructedResponse" rows="9" style="width:100%;box-sizing:border-box" placeholder="Explain your reasoning clearly. Answers are saved locally as you type.">${escape(answers[q.id]||"")}</textarea><p class="notice">This response is not keyword-scored. It remains pending until reviewed against the rubric after submission.</p>`;$("#constructedResponse").addEventListener("input",e=>{answers[q.id]=e.target.value;saveDraft();renderNav();});}$("#previousButton").disabled=current===0;$("#nextButton").disabled=current===SF_QUESTIONS.length-1;renderNav();updateProgress();}
 function renderNav(){$("#questionDots").innerHTML=SF_QUESTIONS.map((q,i)=>`<button type="button" class="dot ${i===current?'current':''} ${answered(q)?'answered':''}" data-i="${i}" aria-label="${q.id}${answered(q)?', answered':''}">${i+1}</button>`).join("");$("#questionDots").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{current=Number(b.dataset.i);render();}));}
 function updateProgress(){const n=SF_QUESTIONS.filter(answered).length;$("#progressText").textContent=`${n} / ${SF_QUESTIONS.length} responses complete`;$("#submitButton").disabled=n<SF_QUESTIONS.length;}
 function scoreObjective(){let correct=0;const byStrand={};objective.forEach(q=>{byStrand[q.strand]||={correct:0,total:0};byStrand[q.strand].total++;if(answers[q.id]===q.answer){correct++;byStrand[q.strand].correct++;}});return {correct,total:objective.length,byStrand};}
 function attemptNumber(s){return (s.attempts?.length||0)+1;}
 function submit(){if(SF_QUESTIONS.some(q=>!answered(q)))return;const s=readState(),auto=scoreObjective(),attempt={assessment_id:ASSESSMENT_ID,assessment_version:VERSION,timestamp:new Date().toISOString(),attempt_number:attemptNumber(s),objective_score:auto.correct,objective_total:auto.total,constructed_total:constructed.length,constructed_scores:{},constructed_responses:Object.fromEntries(constructed.map(q=>[q.id,answers[q.id]])),answers:{...answers},status:"pending_constructed_review",correction_status:"not_started",strand_scores:{},route:"teacher_review"};s.attempts=[...(s.attempts||[]),attempt];s.activeAttempt=attempt.attempt_number;delete s.draftAnswers;s.readiness={course_id:"integrated-science-9",assessment_id:ASSESSMENT_ID,overall_percent:null,strand_scores:{},strengths:[],refresh_priorities:[],route:"teacher_review",attempt:attempt.attempt_number,timestamp:attempt.timestamp,status:"pending_constructed_review"};writeState(s);showResults(attempt,auto);}
 function showResults(attempt,auto){$("#intro").hidden=true;$("#assessment").hidden=true;$("#results").hidden=false;$("#objectiveScore").textContent=`${auto.correct} / ${auto.total}`;$("#resultMessage").textContent="Objective items have been scored. Six constructed explanations require rubric review before the final 30-point mastery score and Unit 1 route can be determined.";$("#domainGrid").innerHTML=Object.entries(auto.byStrand).map(([name,d])=>`<div class="domain-result"><strong>${d.correct} / ${d.total}</strong><span>${escape(name)} objective items</span></div>`).join("");renderReview(attempt);window.scrollTo({top:0,behavior:"smooth"});}
 function renderReview(attempt){$("#constructedReview").innerHTML=constructed.map(q=>`<article class="review-item"><strong>${q.id} · ${escape(q.strand)}</strong><p>${escape(q.prompt)}</p><div class="model-note"><strong>Student response</strong><p>${escape(attempt.constructed_responses[q.id])}</p></div><div class="notice"><strong>Rubric</strong><p>${escape(q.rubric)}</p></div><label>Reviewer score <select data-score="${q.id}"><option value="">Pending</option><option value="1">1 · Demonstrated</option><option value="0">0 · Not yet demonstrated</option></select></label></article>`).join("");$("#constructedReview").querySelectorAll("select").forEach(sel=>sel.addEventListener("change",saveReviewerScores));}
 function saveReviewerScores(){const s=readState(),idx=(s.attempts||[]).findIndex(a=>a.attempt_number===s.activeAttempt);if(idx<0)return;const a=s.attempts[idx];document.querySelectorAll("[data-score]").forEach(sel=>{if(sel.value!=="")a.constructed_scores[sel.dataset.score]=Number(sel.value);});const reviewed=Object.keys(a.constructed_scores).length;if(reviewed===constructed.length)finalizeAttempt(s,idx);else{a.status="pending_constructed_review";s.attempts[idx]=a;writeState(s);$("#finalStatus").textContent=`${reviewed} / ${constructed.length} constructed responses reviewed.`;}}
 function finalizeAttempt(s,idx){const a=s.attempts[idx],constructedPoints=Object.values(a.constructed_scores).reduce((x,y)=>x+y,0),total=a.objective_score+constructedPoints,percent=Math.round(total/30*100);const strands={};SF_QUESTIONS.forEach(q=>{strands[q.strand]||={earned:0,total:0};strands[q.strand].total++;if(q.type==="mc"&&a.answers[q.id]===q.answer)strands[q.strand].earned++;if(q.type==="text"&&a.constructed_scores[q.id]===1)strands[q.strand].earned++;});const strandPercent=Object.fromEntries(Object.entries(strands).map(([k,v])=>[k,Math.round(v.earned/v.total*100)]));const essentialGaps=Object.entries(strandPercent).filter(([,p])=>p<60).map(([k])=>k);const passed=total>=PASS&&essentialGaps.length===0;a.final_score=total;a.final_total=30;a.percent=percent;a.strand_scores=strandPercent;a.essential_gaps=essentialGaps;a.status=passed?"mastered":"refresh_required";a.route=passed?"advance":"unit_0_refresher";a.correction_status=passed?"complete":"required";s.attempts[idx]=a;const strengths=Object.entries(strandPercent).filter(([,p])=>p>=80).map(([k])=>k),refresh=Object.entries(strandPercent).filter(([,p])=>p<80).map(([k])=>k);s.readiness={course_id:"integrated-science-9",assessment_id:ASSESSMENT_ID,overall_percent:percent,strand_scores:strandPercent,strengths,refresh_priorities:refresh,route:passed?"advance":"unit_0_refresher",attempt:a.attempt_number,timestamp:new Date().toISOString(),status:a.status};writeState(s);$("#finalStatus").innerHTML=passed?`<strong>Mastery demonstrated: ${total}/30 (${percent}%).</strong> Official Unit 1 may be released.`:`<strong>${total}/30 (${percent}%).</strong> Targeted refresh is required before release. ${essentialGaps.length?`Essential gaps: ${escape(essentialGaps.join(", "))}.`:""}`;$("#unit1Button").hidden=!passed;$("#refreshButton").hidden=passed;$("#strandFinal").innerHTML=Object.entries(strandPercent).map(([k,p])=>`<div class="domain-result"><strong>${p}%</strong><span>${escape(k)}</span></div>`).join("");}
 function exportJSON(){const s=readState(),blob=new Blob([JSON.stringify({schema_version:"1.0",profile_type:"readiness",course_id:"integrated-science-9",foundations:s.readiness,attempts:s.attempts||[]},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="science-foundations-naib-readiness.json";a.click();URL.revokeObjectURL(url);}
 function start(){loadDraft();$("#intro").hidden=true;$("#results").hidden=true;$("#assessment").hidden=false;render();}
 function retake(){const s=readState();delete s.draftAnswers;writeState(s);answers={};current=0;$("#results").hidden=true;$("#assessment").hidden=false;render();}
 document.addEventListener("DOMContentLoaded",()=>{$("#startButton").addEventListener("click",start);$("#previousButton").addEventListener("click",()=>{if(current>0){current--;render();}});$("#nextButton").addEventListener("click",()=>{if(current<SF_QUESTIONS.length-1){current++;render();}});$("#submitButton").addEventListener("click",submit);$("#retakeButton").addEventListener("click",retake);$("#exportButton").addEventListener("click",exportJSON);$("#printResults").addEventListener("click",()=>window.print());});
})();