window.GEOMETRY_QUESTIONS=[
{"id":"geo-u12m-q01","unit":12,"skill":"L01 · Workspace, Units, Grid & Snap","prompt":"A project is measured in centimeters and uses a 0.5 cm snap. Which point lies on the snap lattice?","options":["(3.2,4.5)","(3.0,4.5)","(3.25,4.1)","(3.1,4.4)"],"answer":1,"answer_text":"(3.0,4.5)","explanation":"Both coordinates are multiples of the 0.5 cm snap increment."},
{"id":"geo-u12m-q02","unit":12,"skill":"L01 · Workspace, Units, Grid & Snap","prompt":"Why should units, workspace/boundary, grid, and snap be verified before drafting?","options":["They determine the drawing's measurement context and precision behavior","They automatically calculate material cost","They guarantee every design is accessible","They convert all exports to PDF"],"answer":0,"answer_text":"They determine the drawing's measurement context and precision behavior","explanation":"Setup errors can propagate through every later dimension and construction."},
{"id":"geo-u12m-q03","unit":12,"skill":"L02 · Precision Lines, Angles & Dimensions","prompt":"A target dimension is 50.0 mm with tolerance ±0.5 mm. Which measured value is outside tolerance?","options":["49.5 mm","50.4 mm","50.5 mm","50.6 mm"],"answer":3,"answer_text":"50.6 mm","explanation":"The acceptable interval is 49.5 mm through 50.5 mm inclusive."},
{"id":"geo-u12m-q04","unit":12,"skill":"L02 · Precision Lines, Angles & Dimensions","prompt":"A target length is 80.0 mm and the measured length is 79.6 mm. What is the absolute error?","options":["0.4 mm","0.5 mm","79.6 mm","159.6 mm"],"answer":0,"answer_text":"0.4 mm","explanation":"Absolute error is |79.6−80.0|=0.4 mm."},
{"id":"geo-u12m-q05","unit":12,"skill":"L03 · Layers, Groups, Visibility & Organization","prompt":"Why place walls and dimensions on separate layers?","options":["To make the scale ratio larger","To control, inspect, lock, hide, and export different information independently","To turn dimensions into physical walls","To remove the need for labels"],"answer":1,"answer_text":"To control, inspect, lock, hide, and export different information independently","explanation":"Layer separation improves revision, auditing, and technical communication."},
{"id":"geo-u12m-q06","unit":12,"skill":"L03 · Layers, Groups, Visibility & Organization","prompt":"Which action best protects verified wall geometry while furniture is being rearranged?","options":["Delete the wall dimensions","Lock the wall layer","Hide every layer","Change drawing units"],"answer":1,"answer_text":"Lock the wall layer","explanation":"Locking prevents accidental edits while allowing other geometry to be revised."},
{"id":"geo-u12m-q07","unit":12,"skill":"L04 · Scale Plans, Openings & Circulation","prompt":"At scale 1:50, how long should a 4.0 m wall appear on the plan?","options":["2 cm","4 cm","8 cm","20 cm"],"answer":2,"answer_text":"8 cm","explanation":"4.0 m=400 cm and 400÷50=8 cm."},
{"id":"geo-u12m-q08","unit":12,"skill":"L04 · Scale Plans, Openings & Circulation","prompt":"A passage measures 2.1 cm on a 1:50 plan. What actual clear width does it represent?","options":["0.42 m","1.05 m","2.1 m","10.5 m"],"answer":1,"answer_text":"1.05 m","explanation":"2.1 cm×50=105 cm=1.05 m."},
{"id":"geo-u12m-q09","unit":12,"skill":"L05 · Area, Perimeter & Material Schedules","prompt":"A 6 m by 4 m floor requires 10% waste allowance. What area should be ordered before package rounding?","options":["24.0 m²","26.4 m²","28.0 m²","30.0 m²"],"answer":1,"answer_text":"26.4 m²","explanation":"Base area is 24 m²; 24×1.10=26.4 m²."},
{"id":"geo-u12m-q10","unit":12,"skill":"L05 · Area, Perimeter & Material Schedules","prompt":"A room is 6 m by 4 m. Trim is installed around the perimeter except across one 0.9 m doorway. How much trim is required?","options":["19.1 m","20.0 m","23.1 m","24.9 m"],"answer":0,"answer_text":"19.1 m","explanation":"Perimeter=2(6+4)=20 m; subtract the 0.9 m doorway."},
{"id":"geo-u12m-q11","unit":12,"skill":"L06 · Transformations, Repetition & Modular Design","prompt":"Translate point P(2,3) by vector ⟨4,−1⟩.","options":["(6,2)","(−2,4)","(6,4)","(3,7)"],"answer":0,"answer_text":"(6,2)","explanation":"Add 4 to x and −1 to y."},
{"id":"geo-u12m-q12","unit":12,"skill":"L06 · Transformations, Repetition & Modular Design","prompt":"A radial design contains 8 identical equally spaced modules. What is its smallest positive rotational symmetry angle?","options":["30°","40°","45°","90°"],"answer":2,"answer_text":"45°","explanation":"360°÷8=45°."},
{"id":"geo-u12m-q13","unit":12,"skill":"L07 · Export, Scale Verification & Design Defense","prompt":"A 5.0 m wall is intended to print at 1:50. What should its printed length be?","options":["5 cm","10 cm","25 cm","50 cm"],"answer":1,"answer_text":"10 cm","explanation":"5.0 m=500 cm; 500÷50=10 cm."},
{"id":"geo-u12m-q14","unit":12,"skill":"L07 · Export, Scale Verification & Design Defense","prompt":"Which submission strategy best supports both presentation and continued technical editing?","options":["Keep only a screenshot","Keep only a printed copy","Preserve an editable/source file and a presentation output such as PDF","Convert every file to a raster image"],"answer":2,"answer_text":"Preserve an editable/source file and a presentation output such as PDF","explanation":"Different recipients need different outputs; source geometry supports continued editing while PDF supports stable presentation."}
];