"use strict";
const ASSESSMENT_QUESTIONS=[
{id:"a01",domain:"Questions & hypotheses",prompt:"Which question identifies a deliberately changed variable, a measurable response, and conditions that can be compared?",options:["Are plants good?","How does salt concentration affect the melting time of equal-mass ice cubes under the same room conditions?","Which ice cube looks nicest?","Should salt be used?"],answer:1,explanation:"A strong investigable question identifies measurable variables and a defined comparison rather than asking for preference or judgment."},
{id:"a02",domain:"Questions & hypotheses",prompt:"Which prediction is testable, directional, and appropriately scoped?",options:["Light is important.","If daily light duration increases, then mean seedling height after 14 days will increase within the tested light-duration range, assuming the other stated growth conditions are controlled.","Plants are interesting.","The result will prove the hypothesis."],answer:1,explanation:"The prediction gives a measurable direction and limits the claim to the tested conditions."},
{id:"a03",domain:"Questions & hypotheses",prompt:"A preregistered prediction is not supported by the results. What is the strongest scientific response?",options:["Rewrite the prediction and pretend the new version came first.","Delete results that disagree.","Report that the results did not support the prediction, evaluate the method and evidence, and revise the explanation if warranted.","Declare the investigation a failure with no useful information."],answer:2,explanation:"Unsupported predictions should be reported honestly. Scientific value comes from evaluating evidence, not forcing results to match expectations."},
{id:"a04",domain:"Variables & controls",prompt:"A student investigates how pendulum length affects period. Which is the independent variable?",options:["Pendulum length","Period","Number of timing trials","Graph scale"],answer:0,explanation:"Pendulum length is the factor deliberately changed."},
{id:"a05",domain:"Variables & controls",prompt:"In the pendulum investigation, why should release angle be controlled?",options:["Because it is the measured outcome.","Because changing it systematically with length could create an alternative explanation for period differences.","Because every controlled variable must equal zero.","Because it determines the graph title."],answer:1,explanation:"A control limits plausible alternative explanations by preventing another factor from changing systematically with the independent variable."},
{id:"a06",domain:"Variables & controls",prompt:"Which statement best describes a confounder?",options:["Any variable written in the notebook.","A variable related to the explanatory condition and the outcome that can create or distort an apparent relationship.","Only an obviously incorrect measurement.","The dependent variable in every experiment."],answer:1,explanation:"A confounder can provide an alternative explanation because it varies with both the explanatory condition and the response."},
{id:"a07",domain:"Measurement",prompt:"Which tool is most appropriate for timing a paper-helicopter fall lasting about 1.5 seconds?",options:["A stopwatch/timer with sub-second resolution","A kilogram scale","A meter stick only","A thermometer"],answer:0,explanation:"The instrument must measure the correct quantity and have resolution appropriate to the event duration."},
{id:"a08",domain:"Measurement",prompt:"Which statement correctly distinguishes accuracy from precision?",options:["Accuracy is closeness to an appropriate reference; precision is closeness among repeated measurements.","Accuracy and precision always mean the same thing.","Precision proves there is no systematic bias.","Accuracy describes graph scale."],answer:0,explanation:"Repeated measurements can be precise yet systematically shifted from an appropriate reference."},
{id:"a09",domain:"Measurement",prompt:"A digital balance displays mass to the nearest 0.1 g. Which reporting choice is most defensible?",options:["18.4 g when that is the displayed measurement","18.43726 g because a calculator can show extra digits","18 g exactly with no stated limitation","18.4 mL"],answer:0,explanation:"Reported digits should be supported by the instrument and method; calculator digits do not create measurement information."},
{id:"a10",domain:"Measurement",prompt:"Five repeated measurements are tightly clustered, but a calibration check shows the instrument reads 0.5 units high. What does this show?",options:["High precision can coexist with systematic bias.","The measurements must be accurate because they agree.","Repeated trials automatically removed the bias.","The range must be zero."],answer:0,explanation:"Consistency among repeated measurements does not guarantee accuracy when a systematic offset is present."},
{id:"a11",domain:"Data integrity",prompt:"Which procedure best protects the integrity of repeated-trial data?",options:["Record every planned trial and document any protocol deviation before deciding how it affects analysis.","Repeat only results that disagree with the prediction.","Delete unusual values before recording them.","Replace raw observations with the mean."],answer:0,explanation:"Raw observations and deviations should remain auditable; analysis decisions should not be based on whether a result is convenient."},
{id:"a12",domain:"Data integrity",prompt:"A trial is far from the others but no procedural failure was observed. What should the investigator do first?",options:["Delete it as an error.","Preserve and flag it, investigate possible explanations, and evaluate its influence transparently.","Change it to the nearest expected value.","Use only that trial."],answer:1,explanation:"An unusual observation is a question for investigation, not an automatic deletion rule."},
{id:"a13",domain:"Tables & graphs",prompt:"Which table heading is scientifically complete?",options:["Time","Fall time (s)","Results","Numbers"],answer:1,explanation:"A complete quantitative heading identifies both the variable and its unit."},
{id:"a14",domain:"Tables & graphs",prompt:"Paper type is categorical and water absorbed is numerical. Which graph is generally appropriate for comparing mean water absorbed among paper types?",options:["A bar chart with paper type on the x-axis and mean water absorbed (g) on the y-axis","A line graph implying paper types form a continuous sequence","An unlabeled sketch","A pie chart of unrelated totals"],answer:0,explanation:"A bar chart can compare a numerical summary across discrete categories; raw trial data should remain available behind the summary."},
{id:"a15",domain:"Tables & graphs",prompt:"Which graph is generally appropriate for examining the association between estimated shade percentage and surface temperature?",options:["Scatter plot","Pie chart","Decorative icon chart","Unscaled diagram"],answer:0,explanation:"A scatter plot displays paired values for two numerical variables."},
{id:"a16",domain:"Tables & graphs",prompt:"Two graphs show the same data but use different y-axis ranges. What is the most defensible conclusion?",options:["The steeper-looking graph is automatically more accurate.","Scale can change visual impression without changing the data, so readers should inspect ranges, intervals, labels, and context.","Every numerical axis must always begin at zero.","Axis choices never affect interpretation."],answer:1,explanation:"Scale is part of data communication. A truncated axis can be useful, but it can also visually magnify small differences if context is ignored."},
{id:"a17",domain:"Data analysis",prompt:"The fall times 1.4 s, 1.5 s, 1.5 s, 1.6 s, and 1.5 s have a mean of:",options:["1.0 s","1.5 s","1.6 s","7.5 s"],answer:1,explanation:"The total is 7.5 s; 7.5 ÷ 5 = 1.5 s."},
{id:"a18",domain:"Data analysis",prompt:"For the same values, what does the 0.2 s range describe?",options:["The observed spread from the minimum to maximum trial.","The accuracy of the timer.","The causal effect of the independent variable.","The number of trials."],answer:0,explanation:"Range equals maximum minus minimum and summarizes observed spread; it does not establish accuracy or causation."},
{id:"a19",domain:"Inference",prompt:"A pattern appears in one limited study. Which conclusion is best calibrated to the evidence?",options:["The pattern was observed under these study conditions and should be evaluated with limitations and additional evidence.","The pattern is universally true.","There are no remaining alternative explanations.","One variable definitely caused the other regardless of design."],answer:0,explanation:"Scientific claims should match the scope, design, uncertainty, and limitations of the evidence."},
{id:"a20",domain:"Inference",prompt:"A study observes that students who sleep longer tend to have higher test scores but does not assign sleep schedules. Which claim is justified directly by that design?",options:["Longer sleep caused every higher score.","Sleep duration and test score were associated in the observed sample.","Higher scores caused longer sleep.","No third variable could matter."],answer:1,explanation:"The observational design supports an association; confounding and direction-of-causation alternatives remain possible."},
{id:"a21",domain:"Causal reasoning",prompt:"Which design change most strengthens causal inference when it is safe and ethical?",options:["Change several factors together.","Deliberately manipulate one factor while controlling or randomizing plausible alternatives where feasible.","Remove the comparison condition.","Select only observations that fit the prediction."],answer:1,explanation:"Controlled manipulation and design features that reduce alternative explanations strengthen causal inference."},
{id:"a22",domain:"CER",prompt:"Which statement is reasoning rather than merely evidence or claim?",options:["The mean fall time was 1.8 s.","Longer rotors had longer mean fall times in this test.","Because rotor geometry can affect interaction with air, and rotor length was deliberately varied while stated conditions were controlled, the measured pattern supports an effect of rotor length under these tested conditions, subject to the listed limitations.","Five trials were recorded."],answer:2,explanation:"Reasoning connects the evidence to the claim using scientific ideas and the design while respecting limitations."},
{id:"a23",domain:"Sources",prompt:"A dramatic news headline makes a scientific claim. Which action provides the strongest source check?",options:["Count how many times it was reposted.","Trace the claim toward the original study, dataset, or agency report and compare its method, scope, and limitations with the headline.","Trust it because it names a scientist.","Reject it automatically because it is news."],answer:1,explanation:"Evidence proximity and method transparency allow the public claim to be compared with the original evidence."},
{id:"a24",domain:"Safety & design",prompt:"During planning, an investigator discovers a hazard that cannot be reasonably controlled with available equipment or supervision. What should happen?",options:["Continue because data are important.","Remove the hazard from the written record.","Revise, replace, or postpone the method before collecting data.","Use fewer trials and proceed anyway."],answer:2,explanation:"Scientific value does not justify an uncontrolled hazard; the method must be made acceptably safe before data collection."}
];
(() => {
 const QUESTIONS=ASSESSMENT_QUESTIONS, FIELD="assessment", TOTAL=QUESTIONS.length, PASSING=Math.ceil(TOTAL*0.80), KEY="khaemenes_science_u01_v1";
 let answers=new Array(TOTAL).fill(null),current=0;
 const $=(s,p=document)=>p.querySelector(s);
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}}
 function saveResult(score,domains){const state=load(),prior=state[FIELD]||{attempts:0,bestScore:0};const attempts=(prior.attempts||0)+1,bestScore=Math.max(prior.bestScore||0,score),passed=bestScore>=PASSING;state[FIELD]={passed,score,total:TOTAL,bestScore,bestPercent:Math.round(bestScore/TOTAL*100),attempts,lastCompletedAt:new Date().toISOString(),domainResults:domains,constructedResponsesRequired:true};if(passed&&!prior.passed)state[FIELD].firstPassedAt=new Date().toISOString();else if(prior.firstPassedAt)state[FIELD].firstPassedAt=prior.firstPassedAt;state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));}
 function escape(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
 function render(){const q=QUESTIONS[current];$("#domainLabel").textContent=q.domain;$("#questionNumber").textContent=`Question ${current+1} of ${TOTAL}`;$("#questionPrompt").textContent=q.prompt;$("#options").innerHTML=q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[current]===i?'checked':''}><span>${escape(o)}</span></label>`).join("");$("#options").querySelectorAll("input").forEach(input=>input.addEventListener("change",e=>{answers[current]=Number(e.target.value);renderDots();updateSubmit();}));$("#previousButton").disabled=current===0;$("#nextButton").disabled=current===TOTAL-1;renderDots();}
 function renderDots(){$("#questionDots").innerHTML=QUESTIONS.map((_,i)=>`<button class="dot ${i===current?'current':''} ${answers[i]!==null?'answered':''}" type="button" data-i="${i}" aria-label="Question ${i+1}${answers[i]!==null?', answered':''}">${i+1}</button>`).join("");$("#questionDots").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{current=Number(b.dataset.i);render();}));}
 function updateSubmit(){$("#submitButton").disabled=answers.some(v=>v===null)}
 function submit(){if(answers.some(v=>v===null))return;const domains={};let score=0;QUESTIONS.forEach((q,i)=>{domains[q.domain]||={correct:0,total:0};domains[q.domain].total++;if(answers[i]===q.answer){score++;domains[q.domain].correct++;}});const passed=score>=PASSING;saveResult(score,domains);$("#assessment").hidden=true;$("#intro").hidden=true;$("#results").hidden=false;$("#score").textContent=`${score} / ${TOTAL}`;$("#resultTitle").textContent=passed?"Objective mastery threshold reached":"Objective mastery threshold not yet reached";$("#resultMessage").textContent=passed?`You reached ${score}/${TOTAL}. Because the course requires at least 80%, the smallest passing whole-number score is ${PASSING}/${TOTAL} (${(PASSING/TOTAL*100).toFixed(1)}%). Complete both constructed responses and the remaining Unit 01 evidence before mastery is recorded.`:`You reached ${score}/${TOTAL}. The whole-number mastery gate is ${PASSING}/${TOTAL} because ${PASSING-1}/${TOTAL} is below 80%. Complete concept corrections before a new attempt.`;$("#domainGrid").innerHTML=Object.entries(domains).map(([name,d])=>`<div class="domain-result"><strong>${d.correct} / ${d.total}</strong><span>${escape(name)}</span></div>`).join("");$("#reviewList").innerHTML=QUESTIONS.map((q,i)=>{const correct=answers[i]===q.answer;return `<article class="review-item ${correct?'correct':'incorrect'}"><strong>${i+1}. ${escape(q.prompt)}</strong><p>Your answer: ${escape(q.options[answers[i]])}</p><p>Correct answer: ${escape(q.options[q.answer])}</p><p>Concept review: ${escape(q.explanation)}</p></article>`;}).join("");window.scrollTo({top:0,behavior:"smooth"});}
 function start(){$("#intro").hidden=true;$("#results").hidden=true;$("#assessment").hidden=false;render();updateSubmit();}
 function retake(){answers=new Array(TOTAL).fill(null);current=0;$("#results").hidden=true;$("#assessment").hidden=false;render();updateSubmit();window.scrollTo({top:0,behavior:"smooth"});}
 document.addEventListener("DOMContentLoaded",()=>{$("#startButton").addEventListener("click",start);$("#previousButton").addEventListener("click",()=>{if(current>0){current--;render();}});$("#nextButton").addEventListener("click",()=>{if(current<TOTAL-1){current++;render();}});$("#submitButton").addEventListener("click",submit);$("#retakeButton").addEventListener("click",retake);$("#printResults").addEventListener("click",()=>window.print());});
})();