"use strict";
(()=>{
 const KEY="khaemenes_science_u03_v1",ROOT="khaemenes_science_integrated9_v1",THEME="khaemenes_theme";
 const REQ=["day01","day02","day03","day04","day05","day06","day07","day08","day09","day10","day11","day12","day13","day14","day15","simulator","circulation","exercise","feedback","case","quiz","assessment","verification","reflection"];
 const DEFAULT={completedPages:[],simulator:{complete:false},circulation:{passed:false,score:0,total:8,bestScore:0,bestPercent:0,attempts:0},exercise:{complete:false},feedback:{passed:false,score:0,total:8,bestScore:0,bestPercent:0,attempts:0},case:{submitted:false,title:""},quiz:{passed:false,score:0,total:20,bestScore:0,bestPercent:0,attempts:0},assessment:{passed:false,score:0,total:30,bestScore:0,bestPercent:0,attempts:0},verification:{complete:false,caseScore:null,caseTotal:40,cr1Score:null,cr1Total:20,cr2Score:null,cr2Total:20,reviewer:"",reviewedAt:null},reflection:{complete:false,text:""},updatedAt:null};
 const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
 function parse(x,d){try{return JSON.parse(x)||d}catch{return d}}
 function root(){return parse(localStorage.getItem(ROOT),{})}
 function prerequisiteMet(){const r=root();return Array.isArray(r.completedUnits)&&r.completedUnits.includes("u02")}
 function load(){const s=parse(localStorage.getItem(KEY),{});return {...DEFAULT,...s,completedPages:Array.isArray(s.completedPages)?s.completedPages:[],simulator:{...DEFAULT.simulator,...(s.simulator||{})},circulation:{...DEFAULT.circulation,...(s.circulation||{})},exercise:{...DEFAULT.exercise,...(s.exercise||{})},feedback:{...DEFAULT.feedback,...(s.feedback||{})},case:{...DEFAULT.case,...(s.case||{})},quiz:{...DEFAULT.quiz,...(s.quiz||{})},assessment:{...DEFAULT.assessment,...(s.assessment||{})},verification:{...DEFAULT.verification,...(s.verification||{})},reflection:{...DEFAULT.reflection,...(s.reflection||{})}}}
 let state=load();
 function scorePassed(rec,threshold){return Boolean(rec?.passed)&&Number(rec.bestScore||rec.score||0)>=threshold}
 function verificationPassed(){const v=state.verification||{};return Boolean(v.complete)&&Number(v.caseScore)>=32&&Number(v.cr1Score)>=16&&Number(v.cr2Score)>=16}
 function done(id){if(/^day\d\d$/.test(id))return state.completedPages.includes(id);if(["simulator","exercise"].includes(id))return !!state[id].complete;if(id==="circulation")return scorePassed(state.circulation,7);if(id==="feedback")return scorePassed(state.feedback,7);if(id==="case")return !!state.case.submitted&&Number(state.verification.caseScore)>=32;if(id==="quiz")return scorePassed(state.quiz,16);if(id==="assessment")return scorePassed(state.assessment,24);if(id==="verification")return verificationPassed();if(id==="reflection")return !!state.reflection.complete;return false}
 function complete(){return prerequisiteMet()&&REQ.every(done)}
 function syncRoot(){const r=root(),set=new Set(Array.isArray(r.completedUnits)?r.completedUnits:[]);if(complete())set.add("u03");else set.delete("u03");const courseSequenceComplete=["u00","u01","u02","u03","u04","u05","u06","u07","u08","u09","u10","u11","u12"].every(id=>set.has(id));localStorage.setItem(ROOT,JSON.stringify({...r,pathway:r.pathway||"Core",completedUnits:[...set],notes:r.notes&&typeof r.notes==="object"?r.notes:{},lastVisitedUnit:prerequisiteMet()?"u03":(r.lastVisitedUnit||"u02"),courseSequenceComplete,updatedAt:new Date().toISOString()}))}
 function save(){if(!prerequisiteMet()){showGate();return}state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));syncRoot();update()}
 function toast(t){const b=$("#toast");if(!b)return;b.textContent=t;b.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>b.hidden=true,3000)}
 function theme(t){const v=["dark","light"].includes(t)?t:"dark";document.documentElement.dataset.theme=v;localStorage.setItem(THEME,v);const b=$("#themeToggle");if(b){b.textContent=v==="dark"?"☼":"◐";b.setAttribute("aria-label",`Switch to ${v==="dark"?"light":"dark"} theme`)}}
 function showGate(){let g=$("#sciencePrerequisiteGate");if(!g){g=document.createElement("section");g.id="sciencePrerequisiteGate";g.setAttribute("role","status");g.style.cssText="position:relative;z-index:50;width:min(920px,calc(100% - 32px));margin:28px auto;padding:24px;border:2px solid #a67b35;border-radius:14px;background:#fff8e7;color:#1d2730;box-shadow:0 14px 34px rgba(0,0,0,.14);text-align:center";const back=location.pathname.includes("/lessons/")?"../../unit-02/":"../unit-02/";g.innerHTML=`<p style="margin:0 0 8px;font-size:.8rem;letter-spacing:.12em;text-transform:uppercase;color:#7a5b1f">Mastery prerequisite</p><h2 style="margin:.2rem 0 .7rem">Unit 03 is locked</h2><p style="max-width:720px;margin:0 auto 16px;line-height:1.6">Unit 02 — Cells &amp; the Organization of Life must be fully completed and mastery-verified before Unit 03 progress can be recorded, including objective and human-scored performance evidence.</p><a href="${back}" style="display:inline-flex;padding:10px 16px;border-radius:7px;background:#17344a;color:#fff;text-decoration:none">Return to Unit 02</a>`;($("main")||document.body).prepend(g)}$$('[data-page-complete],[data-evidence],#caseForm button[type="submit"],#reflectionForm button[type="submit"],#verificationForm button[type="submit"]').forEach(el=>{el.disabled=true;el.setAttribute("aria-disabled","true")})}
 function record(){if(!$("#recordStatus"))return;$("#recordDate").textContent=new Date().toLocaleDateString();$("#recordStatus").textContent=complete()?"Complete · mastery verified":"In progress";$("#recordLessons").textContent=`${state.completedPages.filter(x=>/^day\d\d$/.test(x)).length} of 15`;$("#recordLabs").textContent=`${Number(state.simulator.complete)+Number(done("circulation"))+Number(state.exercise.complete)+Number(done("feedback"))} of 4`;$("#recordCase").textContent=state.case.submitted?(Number(state.verification.caseScore)>=32?`${state.verification.caseScore}/40 · Mastery verified":"Submitted · awaiting/needs rubric mastery"):"Not submitted";$("#recordQuiz").textContent=`${Number(state.quiz.bestScore||state.quiz.score||0)} of 20${done("quiz")?" · Mastery":""}`;$("#recordAssessment").textContent=`${Number(state.assessment.bestScore||state.assessment.score||0)} of 30${done("assessment")?" · Mastery":""}`;if($("#recordConstructed"))$("#recordConstructed").textContent=state.verification.reviewedAt?`CR1 ${state.verification.cr1Score}/20 · CR2 ${state.verification.cr2Score}/20${verificationPassed()?" · Mastery verified":""}`:"Awaiting human scoring";if($("#recordVerification"))$("#recordVerification").textContent=verificationPassed()?"Verified":"Not yet verified";$("#recordReflection").textContent=state.reflection.complete?"Recorded":"Not recorded";$("#recordReflectionText").textContent=state.reflection.text||"No reflection recorded.";if($("#caseScore")&&state.verification.caseScore!=null)$("#caseScore").value=state.verification.caseScore;if($("#cr1Score")&&state.verification.cr1Score!=null)$("#cr1Score").value=state.verification.cr1Score;if($("#cr2Score")&&state.verification.cr2Score!=null)$("#cr2Score").value=state.verification.cr2Score;if($("#reviewerName"))$("#reviewerName").value=state.verification.reviewer||""}
 function update(){if(!prerequisiteMet()){showGate();if($("#unitCompletionStatus"))$("#unitCompletionStatus").textContent="Unit 03 locked · Unit 02 mastery required";record();return}$("#sciencePrerequisiteGate")?.remove();$$("[data-requirement]").forEach(c=>{const d=done(c.dataset.requirement);c.dataset.complete=String(d);const s=$("[data-requirement-status]",c);if(s)s.textContent=d?"Complete":"Not complete"});const n=REQ.filter(done).length,pct=Math.round(n/REQ.length*100);if($("#unitProgressFill"))$("#unitProgressFill").style.width=`${pct}%`;if($("#unitProgressCount"))$("#unitProgressCount").textContent=`${n} of ${REQ.length} requirements`;if($("#unitProgressPercent"))$("#unitProgressPercent").textContent=`${pct}%`;if($("#unitCompletionStatus"))$("#unitCompletionStatus").textContent=complete()?"Unit 03 complete · mastery verified":"Unit 03 in progress";$$("[data-page-complete]").forEach(b=>{const d=state.completedPages.includes(b.dataset.pageComplete);b.disabled=false;b.removeAttribute("aria-disabled");b.setAttribute("aria-pressed",String(d));b.textContent=d?"Lesson Complete ✓":"Mark Lesson Complete"});$$("[data-evidence]").forEach(b=>{const d=!!state[b.dataset.evidence]?.complete;b.disabled=d;b.textContent=d?"Evidence Recorded ✓":"Record Evidence Complete"});record()}
 function submitVerification(e){e.preventDefault();const caseScore=Number($("#caseScore")?.value),cr1Score=Number($("#cr1Score")?.value),cr2Score=Number($("#cr2Score")?.value),reviewer=$("#reviewerName")?.value.trim()||"",ack=Boolean($("#verificationAck")?.checked);if(!Number.isFinite(caseScore)||caseScore<0||caseScore>40||!Number.isFinite(cr1Score)||cr1Score<0||cr1Score>20||!Number.isFinite(cr2Score)||cr2Score<0||cr2Score>20){toast("Enter valid rubric scores: case study 0–40 and each constructed response 0–20.");return}if(!state.case.submitted){toast("Record the case-study submission before educator verification.");return}if(!reviewer||!ack){toast("Enter the reviewer name and confirm the evidence was actually reviewed.");return}const ok=caseScore>=32&&cr1Score>=16&&cr2Score>=16;state.verification={complete:ok,caseScore,caseTotal:40,cr1Score,cr1Total:20,cr2Score,cr2Total:20,reviewer,reviewedAt:new Date().toISOString()};save();toast(ok?"Human-scored Unit 03 mastery evidence verified.":"Scores recorded. One or more performance components remain below the 80% benchmark.")}
 function exportRecord(){if(!prerequisiteMet()){showGate();return}const payload={schema:"khaemenes-science-u03-v2",course:"KH-SCI-IIS9",unit:"u03",prerequisiteUnit02Verified:true,masteryVerified:complete(),exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`KH-SCI-IIS9-unit03-record-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);toast("Unit 03 record exported.")}
 function init(){theme(localStorage.getItem(THEME)||(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark"));$("#themeToggle")?.addEventListener("click",()=>theme(document.documentElement.dataset.theme==="dark"?"light":"dark"));syncRoot();$$("[data-page-complete]").forEach(b=>b.onclick=()=>{if(!prerequisiteMet())return showGate();const s=new Set(state.completedPages);s.has(b.dataset.pageComplete)?s.delete(b.dataset.pageComplete):s.add(b.dataset.pageComplete);state.completedPages=[...s];save()});$$("[data-evidence]").forEach(b=>b.onclick=()=>{if(!prerequisiteMet())return showGate();state[b.dataset.evidence]={...state[b.dataset.evidence],complete:true,completedAt:new Date().toISOString()};save();toast("Evidence recorded.")});$("#caseForm")?.addEventListener("submit",e=>{e.preventDefault();if(!prerequisiteMet())return showGate();if(!$$('.case-check').every(x=>x.checked))return toast("Complete every case criterion before recording submission.");state.case={submitted:true,title:$("#caseTitle")?.value.trim()||"Integrated systems case study",completedAt:new Date().toISOString()};save();toast("Case study recorded; human rubric mastery is still required.")});$("#reflectionForm")?.addEventListener("submit",e=>{e.preventDefault();if(!prerequisiteMet())return showGate();const t=$("#reflectionText")?.value.trim()||"";if(t.length<80)return toast("Add a substantive reflection of at least 80 characters.");state.reflection={complete:true,text:t,completedAt:new Date().toISOString()};save();toast("Reflection recorded.")});$("#verificationForm")?.addEventListener("submit",submitVerification);$("#printPage")?.addEventListener("click",()=>print());$("#exportUnitRecord")?.addEventListener("click",exportRecord);update()}
 window.KhaemenesUnit03={loadState:()=>state,prerequisiteMet,saveState(next){if(!prerequisiteMet())return showGate();state={...state,...next};save()},toast};document.addEventListener("DOMContentLoaded",init)
})();
(()=>{const marker="/courses/science/integrated-science-9/",path=window.location.pathname,at=path.indexOf(marker),base=at>=0?path.slice(0,at+marker.length):new URL("./",window.location.href).pathname;if(document.querySelector('script[data-science-theme-loader]'))return;const script=document.createElement("script");script.src=`${base}science-theme-loader.js`;script.defer=true;script.dataset.scienceThemeLoader="true";document.head.append(script)})();