"use strict";
(()=>{
  const KEY="khaemenes_science_u03_v1",ROOT="khaemenes_science_integrated9_v1",REQ=["day01","day02","day03","day04","day05","day06","day07","day08","day09","day10","day11","day12","day13","day14","day15","simulator","circulation","exercise","feedback","case","quiz","assessment","reflection"],$=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
  let state;
  function parse(x,d){try{return JSON.parse(x)||d}catch{return d}}
  function root(){return parse(localStorage.getItem(ROOT),{})}
  function prerequisiteMet(){const r=root();return Array.isArray(r.completedUnits)&&r.completedUnits.includes("u02")}
  function load(){const s=parse(localStorage.getItem(KEY),{});return {completedPages:Array.isArray(s.completedPages)?s.completedPages:[],simulator:{complete:false,...s.simulator},circulation:{passed:false,score:0,total:8,...s.circulation},exercise:{complete:false,...s.exercise},feedback:{passed:false,score:0,total:8,...s.feedback},case:{submitted:false,title:"",...s.case},quiz:{passed:false,score:0,total:20,...s.quiz},assessment:{passed:false,score:0,total:30,...s.assessment},reflection:{complete:false,text:"",...s.reflection}}}
  function done(id){if(/^day/.test(id))return state.completedPages.includes(id);if(["simulator","exercise"].includes(id))return !!state[id].complete;if(["circulation","feedback","quiz","assessment"].includes(id))return !!state[id].passed;if(id==="case")return !!state.case.submitted;if(id==="reflection")return !!state.reflection.complete;return false}
  function unitComplete(){return prerequisiteMet()&&REQ.every(done)}
  function syncRoot(){const r=root(),c=new Set(Array.isArray(r.completedUnits)?r.completedUnits:[]);if(unitComplete())c.add("u03");else c.delete("u03");const courseSequenceComplete=["u00","u01","u02","u03","u04","u05","u06","u07","u08","u09","u10","u11","u12"].every(id=>c.has(id));localStorage.setItem(ROOT,JSON.stringify({...r,completedUnits:[...c],lastVisitedUnit:prerequisiteMet()?"u03":(r.lastVisitedUnit||"u02"),courseSequenceComplete,updatedAt:new Date().toISOString()}))}
  function toast(t){const b=$("#toast");if(!b)return;b.textContent=t;b.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>b.hidden=true,2600)}
  function showPrerequisiteGate(){let gate=$("#sciencePrerequisiteGate");if(!gate){gate=document.createElement("section");gate.id="sciencePrerequisiteGate";gate.setAttribute("role","status");gate.style.cssText="position:relative;z-index:50;width:min(920px,calc(100% - 32px));margin:28px auto;padding:24px;border:2px solid #a67b35;border-radius:14px;background:#fff8e7;color:#1d2730;box-shadow:0 14px 34px rgba(0,0,0,.14);text-align:center";const back=location.pathname.includes("/lessons/")?"../../unit-02/":"../unit-02/";gate.innerHTML=`<p style="margin:0 0 8px;font-size:.8rem;letter-spacing:.12em;text-transform:uppercase;color:#7a5b1f">Mastery prerequisite</p><h2 style="margin:.2rem 0 .7rem">Unit 03 is locked</h2><p style="max-width:730px;margin:0 auto 16px;line-height:1.6">Unit 02 — Cells &amp; the Organization of Life must be fully completed and mastery-verified before Unit 03 progress can be recorded. This includes the ≥80% objective gates and the human-scored cell model and constructed responses.</p><a href="${back}" style="display:inline-flex;padding:10px 16px;border-radius:7px;background:#17344a;color:#fff;text-decoration:none">Return to Unit 02</a>`;($("main")||document.body).prepend(gate)}$$('[data-page-complete],[data-evidence],#caseForm button[type="submit"],#reflectionForm button[type="submit"]').forEach(el=>{el.disabled=true;el.setAttribute("aria-disabled","true")});$$('a[href*="mastery"],a[href*="assessment"],a[href*="lessons/"]').forEach(a=>{a.setAttribute("aria-disabled","true");a.onclick=e=>{if(!prerequisiteMet()){e.preventDefault();gate.scrollIntoView({behavior:"smooth",block:"center"})}})} )}
  function save(){if(!prerequisiteMet()){showPrerequisiteGate();return}localStorage.setItem(KEY,JSON.stringify(state));syncRoot();update()}
  function record(){if(!$("#recordStatus"))return;$("#recordDate").textContent=new Date().toLocaleDateString();$("#recordStatus").textContent=unitComplete()?"Complete":"In progress";$("#recordLessons").textContent=`${state.completedPages.length} of 15`;$("#recordLabs").textContent=`${Number(state.simulator.complete)+Number(state.circulation.passed)+Number(state.exercise.complete)+Number(state.feedback.passed)} of 4`;$("#recordCase").textContent=state.case.submitted?"Submitted":"Not submitted";$("#recordQuiz").textContent=state.quiz.passed?`${state.quiz.score} of 20 · Passed`:`${state.quiz.score||0} of 20`;$("#recordAssessment").textContent=state.assessment.passed?`${state.assessment.score} of 30 · Passed`:`${state.assessment.score||0} of 30`;$("#recordReflection").textContent=state.reflection.complete?"Recorded":"Not recorded";$("#recordReflectionText").textContent=state.reflection.text||"No reflection recorded."}
  function update(){if(!prerequisiteMet()){showPrerequisiteGate();if($("#unitCompletionStatus"))$("#unitCompletionStatus").textContent="Unit 03 locked · Unit 02 mastery required";return}$("#sciencePrerequisiteGate")?.remove();$$("[data-requirement]").forEach(c=>{const d=done(c.dataset.requirement);c.dataset.complete=String(d);const s=c.querySelector("[data-requirement-status]");if(s)s.textContent=d?"Complete":"Not complete"});const n=REQ.filter(done).length,p=Math.round(n/REQ.length*100);if($("#unitProgressFill"))$("#unitProgressFill").style.width=`${p}%`;if($("#unitProgressCount"))$("#unitProgressCount").textContent=`${n} of ${REQ.length} requirements`;if($("#unitProgressPercent"))$("#unitProgressPercent").textContent=`${p}%`;if($("#unitCompletionStatus"))$("#unitCompletionStatus").textContent=unitComplete()?"Unit 03 complete":"Unit 03 in progress";$$("[data-page-complete]").forEach(b=>{const d=state.completedPages.includes(b.dataset.pageComplete);b.disabled=false;b.removeAttribute("aria-disabled");b.setAttribute("aria-pressed",String(d));b.textContent=d?"Lesson Complete ✓":"Mark Lesson Complete"});$$("[data-evidence]").forEach(b=>{const d=!!state[b.dataset.evidence]?.complete;b.disabled=d;b.textContent=d?"Evidence Recorded ✓":"Record Evidence Complete"});record()}
  function init(){state=load();syncRoot();$$("[data-page-complete]").forEach(b=>b.onclick=()=>{if(!prerequisiteMet())return showPrerequisiteGate();const s=new Set(state.completedPages);s.has(b.dataset.pageComplete)?s.delete(b.dataset.pageComplete):s.add(b.dataset.pageComplete);state.completedPages=[...s];save()});$$("[data-evidence]").forEach(b=>b.onclick=()=>{if(!prerequisiteMet())return showPrerequisiteGate();state[b.dataset.evidence]={...state[b.dataset.evidence],complete:true,completedAt:new Date().toISOString()};save();toast("Evidence recorded.")});if($("#caseForm"))$("#caseForm").onsubmit=e=>{e.preventDefault();if(!prerequisiteMet())return showPrerequisiteGate();if(!$$(".case-check").every(x=>x.checked))return toast("Complete every criterion.");state.case={submitted:true,title:$("#caseTitle").value.trim()||"Integrated systems case study",completedAt:new Date().toISOString()};save();toast("Case study recorded.")};if($("#reflectionForm"))$("#reflectionForm").onsubmit=e=>{e.preventDefault();if(!prerequisiteMet())return showPrerequisiteGate();const t=$("#reflectionText").value.trim();if(t.length<50)return toast("Add at least 50 characters.");state.reflection={complete:true,text:t,completedAt:new Date().toISOString()};save();toast("Reflection recorded.")};if($("#printPage"))$("#printPage").onclick=()=>print();if($("#exportUnitRecord"))$("#exportUnitRecord").onclick=()=>{if(!prerequisiteMet())return showPrerequisiteGate();const blob=new Blob([JSON.stringify({schema:"khaemenes-science-u03-v2",course:"KH-SCI-IIS9",unit:"u03",prerequisiteUnit02Verified:true,state},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="KH-SCI-IIS9-unit03-record.json";a.click()};update()}
  window.KhaemenesUnit03={load:()=>state,prerequisiteMet,save:s=>{if(!prerequisiteMet())return showPrerequisiteGate();state={...state,...s};save()}};
  document.addEventListener("DOMContentLoaded",init)
})();
document.addEventListener("DOMContentLoaded",()=>{const b=document.querySelector("#themeToggle"),k="khaemenes_theme";function a(t){document.documentElement.dataset.theme=t;localStorage.setItem(k,t);if(b)b.textContent=t==="dark"?"☼":"◐"}a(localStorage.getItem(k)||"dark");if(b)b.addEventListener("click",()=>a(document.documentElement.dataset.theme==="dark"?"light":"dark"))});
(()=>{const marker="/courses/science/integrated-science-9/",path=window.location.pathname,at=path.indexOf(marker),base=at>=0?path.slice(0,at+marker.length):new URL("./",window.location.href).pathname;if(document.querySelector('script[data-science-theme-loader]'))return;const script=document.createElement("script");script.src=`${base}science-theme-loader.js`;script.defer=true;script.dataset.scienceThemeLoader="true";document.head.append(script)})();
