import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';
const root=path.resolve('courses/mathematics/geometry');const unit=path.join(root,'units','unit-06');let failures=0;
const check=(ok,label)=>{console.log(`${ok?'OK':'FAIL'} ${label}`);if(!ok)failures++;};const read=r=>fs.readFileSync(path.join(unit,r),'utf8');const exists=r=>fs.existsSync(path.join(unit,r));
for(const rel of ['index.html','unit-map.json','standards-map.json','vocabulary.json','teacher-guide.html','family-guide.html','practice/foundation.html','practice/core.html','practice/extended.html','projects/06-project.html','assessment/mastery-check.html','assessment/answer-key.json'])check(exists(rel),`Unit 06 ${rel} exists`);
const map=JSON.parse(read('unit-map.json'));check(map.unit===6,'unit map belongs to Unit 06');check(map.mastery_target===80,'Unit 06 mastery target is 80%');check(map.lesson_count===8&&Array.isArray(map.lesson_ids)&&map.lesson_ids.length===8,'Unit 06 declares 8 lessons');for(const id of map.lesson_ids||[]){check(exists(`lessons/${id}.html`),`${id} lesson exists`);const key=path.join(root,'teacher-keys',`${id}-key.html`);check(fs.existsSync(key),`${id} teacher key exists`);if(fs.existsSync(key)){const kt=fs.readFileSync(key,'utf8');check(kt.includes(`../units/unit-06/lessons/${id}.html`),`${id} teacher key links student lesson`);check((kt.match(/problem-box/g)||[]).length>=6,`${id} teacher key contains at least 6 keyed responses`);}}
const standards=JSON.parse(read('standards-map.json'));check(standards.mastery_target===80,'standards map preserves 80% mastery');check(Array.isArray(standards.lesson_evidence)&&standards.lesson_evidence.length===8,'standards map has 8 lesson evidence entries');check((map.lesson_ids||[]).every(id=>(standards.lesson_evidence||[]).some(e=>e.lesson_id===id)),'standards evidence matches all declared lesson IDs');check(Array.isArray(standards.human_review_evidence)&&standards.human_review_evidence.length>=4,'standards map separates human-review evidence');
const vocab=JSON.parse(read('vocabulary.json'));check(Array.isArray(vocab.terms)&&vocab.terms.length>=30,'vocabulary is substantive');check(vocab.terms.every(x=>x.term&&x.definition),'vocabulary entries are defined');check(new Set(vocab.terms.map(x=>x.term.toLowerCase())).size===vocab.terms.length,'vocabulary terms are unique');
const upgrade=path.join(root,'assets','unit-06-content-upgrade.js');check(fs.existsSync(upgrade),'Unit 06 hardened content upgrade exists');const sandbox={window:{GEOMETRY_QUESTIONS:[]}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(upgrade,'utf8'),sandbox,{filename:upgrade});const rows=sandbox.window.GEOMETRY_QUESTIONS.filter(q=>Number(q.unit)===6);check(rows.length===40,'runtime bank has 40 items');check(new Set(rows.map(q=>q.id)).size===40,'question IDs are unique');check(new Set(rows.map(q=>q.prompt)).size===40,'question prompts are unique');check(rows.every(q=>Array.isArray(q.options)&&q.options.length===4&&new Set(q.options).size===4),'all items have four unique options');check(rows.every(q=>Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4),'answer indexes are valid');check(rows.every(q=>q.options[q.answer]===q.answer_text),'answer text matches indexed option');check(rows.every(q=>typeof q.explanation==='string'&&q.explanation.trim().length>10),'all items include explanations');for(let l=1;l<=8;l++)check(rows.filter(q=>q.lesson===l).length===5,`Lesson ${String(l).padStart(2,'0')} has 5 assessment items`);check(new Set(rows.map(q=>q.answer)).size>=3,'answer positions are reasonably distributed');
const key=JSON.parse(read('assessment/answer-key.json'));const answers=key.answers||[];check(key.declared_question_count===40,'answer key declares 40 questions');check(key.questions_per_lesson===5,'answer key declares 5 questions per lesson');check(answers.length===40,'answer key contains 40 answers');check(new Set(answers.map(a=>a.id)).size===40,'answer key IDs are unique');const byId=new Map(rows.map(q=>[q.id,q.answer]));check(answers.every(a=>byId.has(a.id)&&byId.get(a.id)===a.answer),'answer key IDs/indexes match runtime bank');
const mastery=read('assessment/mastery-check.html');check(mastery.includes('unit-06-content-upgrade.js'),'mastery check loads hardened Unit 06 bank');check(/count:12/.test(mastery),'mastery check samples 12 questions');check(/units:\[6\]/.test(mastery),'mastery check scopes Unit 06');check(mastery.includes('80%'),'mastery check preserves 80% language');check(mastery.includes('Human-reviewed evidence'),'mastery check separates human-reviewed evidence');check(mastery.includes('Scores and attempt history remain in this browser'),'mastery check documents local attempt evidence');check(mastery.includes('class="skip'),'mastery check exposes skip navigation');
const index=read('index.html');check(index.includes('class="skip'),'Unit 06 index exposes skip navigation');for(const id of map.lesson_ids||[])check(index.includes(`${id}.html`),`Unit 06 index links ${id}`);
const identity={'u06-l01':['Pythagorean theorem','converse','hypotenuse'],'u06-l02':['45-45-90','1:1:√2','exact'],'u06-l03':['30-60-90','1:√3:2','short leg'],'u06-l04':['geometric mean','h²=pq','altitude'],'u06-l05':['SOH-CAH-TOA','reference angle','tangent'],'u06-l06':['inverse','degree mode','tan⁻¹'],'u06-l07':['angle of elevation','angle of depression','line of sight'],'u06-l08':['quadrant bearing','component','resultant']};
const lessonPrompts=[];for(const [id,needles] of Object.entries(identity)){const text=read(`lessons/${id}.html`).toLowerCase();check(needles.every(n=>text.includes(n.toLowerCase())),`${id} contains lesson-specific mathematical identity`);const prompts=[...text.matchAll(/problem-prompt[^>]*>([^<]+)/g)].map(m=>m[1].trim());lessonPrompts.push({id,prompts});check(prompts.length>=6,`${id} contains at least 6 printable problems`);}check(new Set(lessonPrompts.map(x=>x.prompts.join('|'))).size===lessonPrompts.length,'lesson worksheet prompt sets are differentiated');
if(failures){console.error(`Unit 06 validation failed: ${failures} problem(s).`);process.exit(1);}console.log('Unit 06 validation passed.');