import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';
const root=path.resolve('courses/mathematics/geometry');const unit=path.join(root,'units','unit-05');let failures=0;
const check=(ok,label)=>{console.log(`${ok?'OK':'FAIL'} ${label}`);if(!ok)failures++;};const readRel=r=>fs.readFileSync(path.join(unit,r),'utf8');const existsRel=r=>fs.existsSync(path.join(unit,r));
for(const rel of ['index.html','unit-map.json','standards-map.json','vocabulary.json','teacher-guide.html','family-guide.html','practice/foundation.html','practice/core.html','practice/extended.html','projects/05-project.html','assessment/mastery-check.html','assessment/answer-key.json'])check(existsRel(rel),`Unit 05 ${rel} exists`);
const map=JSON.parse(readRel('unit-map.json'));check(map.unit===5,'unit map belongs to Unit 05');check(map.mastery_target===80,'Unit 05 mastery target is 80%');check(map.lesson_count===7&&Array.isArray(map.lesson_ids)&&map.lesson_ids.length===7,'Unit 05 declares 7 lessons');for(const id of map.lesson_ids||[])check(existsRel(`lessons/${id}.html`),`${id} lesson exists`);
const standards=JSON.parse(readRel('standards-map.json'));check(standards.mastery_target===80,'standards map preserves 80% mastery target');check(standards.lesson_evidence&&Object.keys(standards.lesson_evidence).length===7,'standards map has 7 lesson evidence entries');check((map.lesson_ids||[]).every(id=>Object.prototype.hasOwnProperty.call(standards.lesson_evidence||{},id)),'standards evidence matches declared lesson IDs');
const vocab=JSON.parse(readRel('vocabulary.json'));check(Array.isArray(vocab.terms)&&vocab.terms.length>=21,'vocabulary is substantive');check(Array.isArray(vocab.terms)&&new Set(vocab.terms.map(x=>String(x.term||'').trim().toLowerCase())).size===vocab.terms.length,'vocabulary terms are unique');
const upgrade=path.join(root,'assets','unit-05-content-upgrade.js');check(fs.existsSync(upgrade),'Unit 05 hardened content upgrade exists');const sandbox={window:{GEOMETRY_QUESTIONS:[]}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(upgrade,'utf8'),sandbox,{filename:upgrade});const rows=sandbox.window.GEOMETRY_QUESTIONS.filter(q=>Number(q.unit)===5);check(rows.length===35,'runtime bank has 35 items');check(new Set(rows.map(q=>q.id)).size===35,'question IDs are unique');check(new Set(rows.map(q=>q.prompt)).size===35,'prompts are unique');check(rows.every(q=>Array.isArray(q.options)&&q.options.length===4&&new Set(q.options).size===4),'all items have four unique options');check(rows.every(q=>Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4),'answer indexes valid');check(rows.every(q=>q.options[q.answer]===q.answer_text),'answer text matches indexed option');check(rows.every(q=>typeof q.explanation==='string'&&q.explanation.trim().length>10),'all explanations present');for(let l=1;l<=7;l++)check(rows.filter(q=>q.lesson===l).length===5,`Lesson ${String(l).padStart(2,'0')} has 5 assessment items`);check([0,1,2,3].filter(i=>rows.some(q=>q.answer===i)).length===4,'answer positions use all four indexes');
const key=JSON.parse(readRel('assessment/answer-key.json'));const answers=key.answers||key.items||[];check(key.declared_question_count===35,'answer key declares 35 questions');check(answers.length===35,'answer key contains 35 answers');check(new Set(answers.map(a=>a.id)).size===35,'answer key IDs unique');const byId=new Map(rows.map(q=>[q.id,q.answer]));check(answers.every(a=>byId.has(a.id)&&byId.get(a.id)===a.answer),'answer key IDs/indexes match runtime bank');
const mastery=readRel('assessment/mastery-check.html');check(mastery.includes('unit-05-content-upgrade.js'),'mastery check loads hardened Unit 05 bank');check(/count:12/.test(mastery),'mastery check samples 12 questions');check(/units:\[5\]/.test(mastery),'mastery check scopes Unit 05');check(mastery.includes('80%'),'mastery check preserves 80% language');check(mastery.includes('Human-reviewed evidence'),'mastery check separates human-reviewed evidence');check(mastery.includes('Scores and attempt history remain in this browser'),'mastery check documents attempt evidence');check(mastery.includes('class="skip'),'mastery check exposes skip navigation');
const index=readRel('index.html');check(index.includes('class="skip'),'Unit 05 index exposes skip navigation');for(const id of map.lesson_ids||[])check(index.includes(`${id}.html`),`Unit 05 index links ${id}`);
const identityChecks={
'u05-l01':['center of dilation','scale factor'],'u05-l02':['rigid','dilation'],'u05-l03':['AA','correspond'],'u05-l04':['SSS','SAS'],'u05-l05':['Side-Splitter','parallel'],'u05-l06':['scale','units'],'u05-l07':['shadow','mirror']};
for(const [id,needles] of Object.entries(identityChecks)){const text=readRel(`lessons/${id}.html`);check(needles.every(n=>text.toLowerCase().includes(n.toLowerCase())),`${id} contains lesson-specific mathematical identity`);}
if(failures){console.error(`Unit 05 validation failed: ${failures} problem(s).`);process.exit(1);}console.log('Unit 05 validation passed.');