"use strict";

const CACHE_VERSION = "khaemenes-high-design-v20";
const PRECACHE_FILES = [
  "./",
  "./index.html",
  "./README.md",
  "./LICENSE",
  "./SECURITY.md",
  "./CONTRIBUTING.md",
  "./manifest.webmanifest",
  "./grades/grade-09/",
  "./grades/grade-09/index.html",
  "./grades/grade-09/course-catalog.json",
  "./grades/grade-09/planner.json",
  "./courses/mathematics/pre-algebra/",
  "./courses/mathematics/pre-algebra/index.html",
  "./courses/mathematics/pre-algebra/course-ui.css",
  "./courses/mathematics/pre-algebra/course-map.json",
  "./courses/mathematics/pre-algebra/diagnostic/",
  "./courses/mathematics/pre-algebra/diagnostic/index.html",
  "./courses/mathematics/pre-algebra/units/unit-01/",
  "./courses/mathematics/pre-algebra/units/unit-01/README.md",
  "./courses/mathematics/pre-algebra/units/unit-01/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-01/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-01/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-01/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-01/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-01/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-01/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-01/index.html",
  "./courses/mathematics/pre-algebra/units/unit-01/lessons/lesson-01-number-systems.html",
  "./courses/mathematics/pre-algebra/units/unit-01/lessons/lesson-02-factors-multiples.html",
  "./courses/mathematics/pre-algebra/units/unit-01/lessons/lesson-03-primes-divisibility.html",
  "./courses/mathematics/pre-algebra/units/unit-01/lessons/lesson-04-gcf-lcm.html",
  "./courses/mathematics/pre-algebra/units/unit-01/lessons/lesson-05-order-operations.html",
  "./courses/mathematics/pre-algebra/units/unit-01/lessons/lesson-06-estimation-reasonableness.html",
  "./courses/mathematics/pre-algebra/units/unit-01/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-01/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-01/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-01/projects/number-systems-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-01/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-01/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-01/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-01/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-02/",
  "./courses/mathematics/pre-algebra/units/unit-02/README.md",
  "./courses/mathematics/pre-algebra/units/unit-02/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-02/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-02/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-02/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-02/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-02/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-02/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-02/index.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-01-integers-in-context.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-02-opposites-absolute-value.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-03-compare-order-integers.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-04-adding-integers.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-05-subtracting-integers.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-06-multiply-divide-integers.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-07-coordinate-plane-signed-change.html",
  "./courses/mathematics/pre-algebra/units/unit-02/lessons/lesson-08-multi-step-integer-applications.html",
  "./courses/mathematics/pre-algebra/units/unit-02/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-02/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-02/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-02/projects/signed-data-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-02/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-02/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-02/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-02/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-03/README.md",
  "./courses/mathematics/pre-algebra/units/unit-03/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-03/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-03/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-03/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-03/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-03/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-03/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-03/index.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-01-rational-numbers-fraction-meaning.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-02-equivalent-fractions-simplifying.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-03-compare-order-rational-numbers.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-04-add-subtract-rational-numbers.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-05-multiply-fractions-mixed-numbers.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-06-divide-fractions-complex-fractions.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-07-decimal-operations-repeating-decimals.html",
  "./courses/mathematics/pre-algebra/units/unit-03/lessons/lesson-08-conversions-estimation-applications.html",
  "./courses/mathematics/pre-algebra/units/unit-03/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-03/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-03/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-03/projects/rational-quantity-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-03/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-03/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-03/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-03/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-04/README.md",
  "./courses/mathematics/pre-algebra/units/unit-04/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-04/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-04/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-04/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-04/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-04/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-04/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-04/index.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-01-ratio-meaning-equivalent-ratios.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-02-ratio-tables-double-number-lines.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-03-rates-unit-rates-fair-comparisons.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-04-proportional-tables-graphs-equations.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-05-solving-proportions-direct-variation.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-06-scale-drawings-maps-similar-figures.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-07-proportional-vs-nonproportional.html",
  "./courses/mathematics/pre-algebra/units/unit-04/lessons/lesson-08-conversions-multistep-proportional-modelling.html",
  "./courses/mathematics/pre-algebra/units/unit-04/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-04/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-04/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-04/projects/community-scale-rate-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-04/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-04/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-04/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-04/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-05/",
  "./courses/mathematics/pre-algebra/units/unit-05/README.md",
  "./courses/mathematics/pre-algebra/units/unit-05/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-05/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-05/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-05/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-05/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-05/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-05/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-05/index.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-01-percent-meaning-benchmarks-equivalent-forms.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-02-finding-percent-of-quantity.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-03-finding-percent-rate-or-whole.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-04-percent-increase-decrease-relative-change.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-05-discounts-tax-tips-commission.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-06-markup-profit-loss-break-even.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-07-simple-interest-fees-financial-comparisons.html",
  "./courses/mathematics/pre-algebra/units/unit-05/lessons/lesson-08-percentage-points-repeated-change-decisions.html",
  "./courses/mathematics/pre-algebra/units/unit-05/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-05/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-05/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-05/projects/consumer-financial-decision-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-05/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-05/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-05/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-05/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-06/",
  "./courses/mathematics/pre-algebra/units/unit-06/README.md",
  "./courses/mathematics/pre-algebra/units/unit-06/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-06/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-06/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-06/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-06/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-06/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-06/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-06/index.html",
  "./courses/mathematics/pre-algebra/units/unit-06/lessons/lesson-01-exponent-meaning-powers-grouping.html",
  "./courses/mathematics/pre-algebra/units/unit-06/lessons/lesson-02-zero-negative-exponents-patterns.html",
  "./courses/mathematics/pre-algebra/units/unit-06/lessons/lesson-03-exponent-properties-equivalent-expressions.html",
  "./courses/mathematics/pre-algebra/units/unit-06/lessons/lesson-04-square-cube-roots-perfect-powers.html",
  "./courses/mathematics/pre-algebra/units/unit-06/lessons/lesson-05-estimating-irrational-roots.html",
  "./courses/mathematics/pre-algebra/units/unit-06/lessons/lesson-06-scientific-notation-powers-ten.html",
  "./courses/mathematics/pre-algebra/units/unit-06/lessons/lesson-07-operations-scientific-notation-applications.html",
  "./courses/mathematics/pre-algebra/units/unit-06/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-06/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-06/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-06/projects/scale-of-universe-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-06/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-06/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-06/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-06/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-07/",
  "./courses/mathematics/pre-algebra/units/unit-07/README.md",
  "./courses/mathematics/pre-algebra/units/unit-07/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-07/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-07/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-07/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-07/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-07/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-07/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-07/index.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-01-variables-terms-coefficients-constants.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-02-translating-words-contexts-expressions.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-03-evaluating-expressions-substitution.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-04-properties-operations-equivalent-structure.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-05-distributive-property-factoring.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-06-combining-like-terms-simplifying.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-07-formulas-multivariable-expressions.html",
  "./courses/mathematics/pre-algebra/units/unit-07/lessons/lesson-08-structural-modelling-patterns-error-analysis.html",
  "./courses/mathematics/pre-algebra/units/unit-07/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-07/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-07/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-07/projects/algebraic-model-design-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-07/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-07/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-07/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-07/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-08/",
  "./courses/mathematics/pre-algebra/units/unit-08/README.md",
  "./courses/mathematics/pre-algebra/units/unit-08/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-08/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-08/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-08/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-08/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-08/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-08/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-08/index.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-01-equality-solutions-balance-model.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-02-one-step-addition-subtraction.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-03-one-step-multiplication-division.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-04-two-step-equations-operation-order.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-05-multistep-distribution-like-terms.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-06-variables-both-sides-identities-contradictions.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-07-rearranging-formulas-literal-equations.html",
  "./courses/mathematics/pre-algebra/units/unit-08/lessons/lesson-08-context-equations-verification-error-analysis.html",
  "./courses/mathematics/pre-algebra/units/unit-08/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-08/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-08/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-08/projects/equation-formula-design-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-08/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-08/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-08/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-08/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-09/README.md",
  "./courses/mathematics/pre-algebra/units/unit-09/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-09/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-09/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-09/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-09/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-09/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-09/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-09/index.html",
  "./courses/mathematics/pre-algebra/units/unit-09/lessons/lesson-01-inequality-meaning-symbols-solution-sets.html",
  "./courses/mathematics/pre-algebra/units/unit-09/lessons/lesson-02-number-line-graphs-interval-descriptions.html",
  "./courses/mathematics/pre-algebra/units/unit-09/lessons/lesson-03-one-step-inequalities-order-preservation.html",
  "./courses/mathematics/pre-algebra/units/unit-09/lessons/lesson-04-negative-multipliers-reversal.html",
  "./courses/mathematics/pre-algebra/units/unit-09/lessons/lesson-05-multistep-variables-both-sides.html",
  "./courses/mathematics/pre-algebra/units/unit-09/lessons/lesson-06-compound-inequalities-and-or.html",
  "./courses/mathematics/pre-algebra/units/unit-09/lessons/lesson-07-contextual-constraints-discrete-solutions.html",
  "./courses/mathematics/pre-algebra/units/unit-09/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-09/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-09/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-09/projects/constraint-design-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-09/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-09/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-09/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-09/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-10/README.md",
  "./courses/mathematics/pre-algebra/units/unit-10/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-10/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-10/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-10/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-10/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-10/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-10/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-10/index.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-01-coordinate-plane-ordered-pairs-quadrants.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-02-patterns-sequences-rules.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-03-relations-inputs-outputs-functions.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-04-tables-graphs-equations-words.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-05-rate-change-tables-graphs-contexts.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-06-slope-intercepts-linear-equations.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-07-linear-nonlinear-function-notation.html",
  "./courses/mathematics/pre-algebra/units/unit-10/lessons/lesson-08-linear-modelling-prediction-residuals.html",
  "./courses/mathematics/pre-algebra/units/unit-10/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-10/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-10/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-10/projects/linear-relationship-data-story-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-10/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-10/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-10/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-10/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-11/README.md",
  "./courses/mathematics/pre-algebra/units/unit-11/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-11/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-11/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-11/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-11/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-11/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-11/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-11/index.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-01-measurement-systems-units-precision.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-02-angles-lines-transversals-polygons.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-03-perimeter-circumference-composite-boundaries.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-04-area-polygons-circles-composite-figures.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-05-scale-drawings-similarity-dilations.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-06-right-triangles-pythagorean-distance.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-07-surface-area-nets-volume.html",
  "./courses/mathematics/pre-algebra/units/unit-11/lessons/lesson-08-coordinate-geometry-design-constraints-error.html",
  "./courses/mathematics/pre-algebra/units/unit-11/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-11/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-11/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-11/projects/accessible-space-scale-design-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-11/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-11/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-11/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-11/vocabulary.json",
  "./courses/mathematics/pre-algebra/units/unit-12/README.md",
  "./courses/mathematics/pre-algebra/units/unit-12/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-12/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-12/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-12/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-12/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-12/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-12/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-12/index.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-01-data-questions-variables-populations-samples.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-02-frequency-tables-dot-plots-histograms-box-plots.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-03-measures-center-mean-median-mode-weighted-mean.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-04-variability-range-iqr-mad-outliers.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-05-comparing-distributions-misleading-displays.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-06-probability-models-sample-spaces-relative-frequency.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-07-compound-probability-tree-diagrams-simulation.html",
  "./courses/mathematics/pre-algebra/units/unit-12/lessons/lesson-08-sampling-bias-association-evidence-decisions.html",
  "./courses/mathematics/pre-algebra/units/unit-12/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-12/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-12/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-12/projects/community-data-evidence-investigation.html",
  "./courses/mathematics/pre-algebra/units/unit-12/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-12/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-12/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-12/vocabulary.json"
,
  "./courses/mathematics/pre-algebra/units/unit-13/README.md",
  "./courses/mathematics/pre-algebra/units/unit-13/assessment/answer-key.json",
  "./courses/mathematics/pre-algebra/units/unit-13/assessment/mastery-check.html",
  "./courses/mathematics/pre-algebra/units/unit-13/assets/assessment-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-13/assets/lesson-engine.js",
  "./courses/mathematics/pre-algebra/units/unit-13/assets/unit-dashboard.js",
  "./courses/mathematics/pre-algebra/units/unit-13/assets/unit.css",
  "./courses/mathematics/pre-algebra/units/unit-13/family-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-13/index.html",
  "./courses/mathematics/pre-algebra/units/unit-13/lessons/lesson-01-frame-meaningful-safe-answerable-question.html",
  "./courses/mathematics/pre-algebra/units/unit-13/lessons/lesson-02-select-variables-mathematics-data-representations.html",
  "./courses/mathematics/pre-algebra/units/unit-13/lessons/lesson-03-build-calculate-verify-revise-model.html",
  "./courses/mathematics/pre-algebra/units/unit-13/lessons/lesson-04-test-assumptions-sensitivity-uncertainty-fairness.html",
  "./courses/mathematics/pre-algebra/units/unit-13/lessons/lesson-05-communicate-defend-reflect-readiness.html",
  "./courses/mathematics/pre-algebra/units/unit-13/practice/core.html",
  "./courses/mathematics/pre-algebra/units/unit-13/practice/extended.html",
  "./courses/mathematics/pre-algebra/units/unit-13/practice/foundation.html",
  "./courses/mathematics/pre-algebra/units/unit-13/projects/mathematical-modelling-capstone-portfolio.html",
  "./courses/mathematics/pre-algebra/units/unit-13/standards-map.json",
  "./courses/mathematics/pre-algebra/units/unit-13/teacher-guide.html",
  "./courses/mathematics/pre-algebra/units/unit-13/tools/modelling-verification-studio.html",
  "./courses/mathematics/pre-algebra/units/unit-13/unit-map.json",
  "./courses/mathematics/pre-algebra/units/unit-13/vocabulary.json",
  "./courses/mathematics/pre-algebra/assessments/",
  "./courses/mathematics/pre-algebra/assessments/index.html",
  "./courses/mathematics/pre-algebra/assessments/midterm-units-01-07.html",
  "./courses/mathematics/pre-algebra/assessments/final-exam-36-weeks.html",
  "./courses/mathematics/pre-algebra/assessments/administration-guide.html",
  "./courses/mathematics/pre-algebra/assessments/assessment-map.json",
  "./courses/mathematics/pre-algebra/assessments/answer-keys.json",
  "./courses/mathematics/pre-algebra/assessments/assets/assessment-suite.css",
  "./courses/mathematics/pre-algebra/assessments/assets/exam-engine.js",
  "./courses/mathematics/pre-algebra/records/README.md",
  "./courses/mathematics/pre-algebra/records/course-completion-certificate.html",
  "./docs/releases/ASSESSMENT_RECORDS_RELEASE.md",
  "./docs/audits/ASSESSMENT_RECORDS_VALIDATION.md",
];

self.addEventListener("install", event => {
  event.waitUntil(caches.open(CACHE_VERSION).then(cache => Promise.allSettled(PRECACHE_FILES.map(path => cache.add(new Request(path, { cache: "reload" }))))).then(() => self.skipWaiting()));
});

self.addEventListener("activate", event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith("khaemenes-high-") && key !== CACHE_VERSION).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});

function fallbackFor(url) {
  const path = url.pathname;
  if (path.includes("/units/unit-13")) return "./courses/mathematics/pre-algebra/units/unit-13/index.html";
  if (path.includes("/units/unit-12")) return "./courses/mathematics/pre-algebra/units/unit-12/index.html";
  if (path.includes("/units/unit-11")) return "./courses/mathematics/pre-algebra/units/unit-11/index.html";
  if (path.includes("/units/unit-10")) return "./courses/mathematics/pre-algebra/units/unit-10/index.html";
  if (path.includes("/units/unit-09")) return "./courses/mathematics/pre-algebra/units/unit-09/index.html";
  if (path.includes("/units/unit-08")) return "./courses/mathematics/pre-algebra/units/unit-08/index.html";
  if (path.includes("/units/unit-07")) return "./courses/mathematics/pre-algebra/units/unit-07/index.html";
  if (path.includes("/units/unit-06")) return "./courses/mathematics/pre-algebra/units/unit-06/index.html";
  if (path.includes("/units/unit-05")) return "./courses/mathematics/pre-algebra/units/unit-05/index.html";
  if (path.includes("/units/unit-04")) return "./courses/mathematics/pre-algebra/units/unit-04/index.html";
  if (path.includes("/units/unit-03")) return "./courses/mathematics/pre-algebra/units/unit-03/index.html";
  if (path.includes("/units/unit-02")) return "./courses/mathematics/pre-algebra/units/unit-02/index.html";
  if (path.includes("/units/unit-01")) return "./courses/mathematics/pre-algebra/units/unit-01/index.html";
  if (path.includes("/courses/mathematics/pre-algebra/assessments")) return "./courses/mathematics/pre-algebra/assessments/index.html";
  if (path.includes("/courses/mathematics/pre-algebra/records")) return "./courses/mathematics/pre-algebra/records/course-completion-certificate.html";
  if (path.includes("/courses/mathematics/pre-algebra/diagnostic")) return "./courses/mathematics/pre-algebra/diagnostic/index.html";
  if (path.includes("/courses/mathematics/pre-algebra")) return "./courses/mathematics/pre-algebra/index.html";
  if (path.includes("/grades/grade-09")) return "./grades/grade-09/index.html";
  return "./index.html";
}

self.addEventListener("fetch", event => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === "navigate") {
    event.respondWith(fetch(request).then(response => { if (response && response.ok) { const copy = response.clone(); caches.open(CACHE_VERSION).then(cache => cache.put(request, copy)); } return response; }).catch(async () => (await caches.match(request)) || (await caches.match(fallbackFor(url))) || caches.match("./index.html")));
    return;
  }
  event.respondWith(caches.match(request).then(cached => { const network = fetch(request).then(response => { if (response && response.ok) { const copy = response.clone(); caches.open(CACHE_VERSION).then(cache => cache.put(request, copy)); } return response; }).catch(() => cached); return cached || network; }));
});

self.addEventListener("message", event => { if (event.data === "SKIP_WAITING") self.skipWaiting(); });
