"use strict";
const QUIZ_QUESTIONS=[
{id:"q01",domain:"Questions",prompt:"Which question is directly investigable with measurements and a defined comparison?",options:["Which paper airplane looks best?","How does wing length in centimeters affect flight distance in meters for airplanes made from the same paper and design?","Should everyone enjoy building paper airplanes?","Is flight interesting?"],answer:1,explanation:"The question identifies a measurable changed variable, measurable outcome, and a comparison that can be investigated."},
{id:"q02",domain:"Variables",prompt:"A student deliberately changes ramp height and measures how far the same toy car travels. Which statement is correct?",options:["Ramp height is the dependent variable.","Distance traveled is the dependent variable.","The toy car is the independent variable.","Distance traveled should be controlled."],answer:1,explanation:"Distance traveled is the measured response; ramp height is deliberately changed."},
{id:"q03",domain:"Definitions",prompt:"Which is the strongest operational definition of plant growth for a two-week investigation?",options:["Growth means the plant looks healthier.","Growth is the change in stem height, measured in centimeters from the same reference point on Day 1 and Day 14.","Growth means doing well.","Growth is whatever difference the observer notices."],answer:1,explanation:"An operational definition states exactly how the variable is measured so another investigator can reproduce it."},
{id:"q04",domain:"Design",prompt:"Why are repeated trials useful in a fair test?",options:["They guarantee the prediction is correct.","They characterize variation and provide more evidence about the typical result.","They remove systematic bias automatically.","They make controlled variables unnecessary."],answer:1,explanation:"Replication helps reveal random variation and estimate a typical result, but it does not automatically correct systematic bias."},
{id:"q05",domain:"Measurement",prompt:"A ruler has millimeter markings. Which report best respects the instrument rather than inventing unsupported precision?",options:["A length with many extra decimal places because a calculator can display them.","A length reported at a precision defensible from the ruler and measurement procedure.","Only the word 'long.'","Any number without a unit."],answer:1,explanation:"Reported precision should be supported by the measuring instrument and procedure, not by calculator display digits."},
{id:"q06",domain:"Measurement",prompt:"Four measurements are 9.8 cm, 9.8 cm, 9.9 cm, and 9.8 cm. What can be concluded from these values alone?",options:["They are highly precise, but accuracy cannot be established without an appropriate reference.","They are definitely accurate.","They prove the instrument has no systematic bias.","They establish causation."],answer:0,explanation:"The values cluster closely, indicating precision. Accuracy and systematic bias require additional evidence or reference checks."},
{id:"q07",domain:"Data integrity",prompt:"One recorded trial is far from the others. What is the strongest first response?",options:["Delete it because it weakens the pattern.","Replace it with the mean.","Preserve it, inspect the procedure and notes for a documented cause, and repeat only according to a defensible rule.","Use it as the only result because unusual data are always most important."],answer:2,explanation:"An unusual observation remains part of the audit trail unless a scientifically justified, documented analysis rule supports different treatment."},
{id:"q08",domain:"Graphing",prompt:"Paper type is categorical and mean water absorbed is numerical. Which display is generally appropriate for comparing the paper categories?",options:["A bar chart with paper type on the x-axis and clearly identified mean water absorbed on the y-axis.","A line graph that implies paper types occur in a continuous sequence.","A pie chart of unrelated totals.","An unlabeled graph with no units."],answer:0,explanation:"A bar chart can compare a numerical summary across discrete categories; raw trials should remain available to show the basis of the summary."},
{id:"q09",domain:"Graph integrity",prompt:"Two graphs use the same data but different y-axis ranges. Which statement is most scientifically defensible?",options:["The graph with the steepest-looking pattern is automatically more truthful.","Axis range can change visual impression without changing the underlying numbers, so scale and labels must be inspected.","All graphs must begin every numerical axis at zero regardless of purpose.","Axis choices do not affect interpretation."],answer:1,explanation:"Scale changes visual emphasis. Readers need the axis values and context to judge magnitude honestly."},
{id:"q10",domain:"Study types",prompt:"Researchers record students' existing sleep duration and test scores without assigning sleep schedules. What does the design directly establish?",options:["A controlled causal effect of sleep duration.","An observational relationship that may be associated but can contain confounding or reverse-causation explanations.","That test scores cause sleep duration.","That no scientific conclusion is possible."],answer:1,explanation:"Because sleep was observed rather than assigned, the study can examine association but does not by itself isolate a causal effect."},
{id:"q11",domain:"Causal reasoning",prompt:"Ice-cream sales and sunburn cases both rise during hot summer periods. Which is a plausible confounding explanation?",options:["Ice cream must cause sunburn.","Sunburn must cause ice-cream purchases.","Hot sunny weather can increase both ice-cream purchases and sun exposure.","Any correlation proves both variables are inaccurate."],answer:2,explanation:"A third variable—hot sunny weather—can plausibly influence both observed variables."},
{id:"q12",domain:"CER",prompt:"Which statement best describes scientific reasoning in a CER?",options:["It repeats the evidence using different words.","It explains why the evidence bears on the claim using relevant scientific ideas, study design, and appropriate limitations.","It is a personal opinion about whether the result is interesting.","It lists sources without connecting them to the claim."],answer:1,explanation:"Reasoning supplies the logical and scientific connection between evidence and claim and should respect design limitations."},
{id:"q13",domain:"Sources",prompt:"A news headline makes a strong scientific claim. What is the strongest source-literacy response?",options:["Trust the headline if it sounds scientific.","Trace the claim toward the original study, dataset, or agency report and compare the original evidence and limitations with the headline wording.","Reject every news report automatically.","Count how many times the claim was reposted."],answer:1,explanation:"Tracing toward original evidence allows the reader to inspect method, scope, limitations, and whether the public wording preserves them."},
{id:"q14",domain:"Uncertainty",prompt:"Which statement correctly distinguishes random variation from systematic bias?",options:["Repeating measurements always eliminates both.","Random variation can cause unpredictable trial-to-trial differences, while systematic bias can shift measurements consistently and may persist across repetitions.","Systematic bias is simply any unusual data point.","Random variation means the experiment was conducted incorrectly."],answer:1,explanation:"Replication can help characterize some random variation, while systematic bias often requires calibration, reference checks, sampling changes, or redesign."},
{id:"q15",domain:"Safety and design",prompt:"A planned investigation has a hazard that cannot be reasonably controlled with the available equipment and supervision. What should happen before data collection?",options:["Continue because completing the dataset is more important.","Hide the hazard from the record.","Revise, replace, or postpone the method until the risk can be acceptably controlled.","Collect fewer trials so exposure is shorter."],answer:2,explanation:"Scientific work does not justify an uncontrolled hazard. The design must be changed or postponed before beginning."}
];
(() => {
 const QUESTIONS=QUIZ_QUESTIONS, FIELD="quiz", TOTAL=QUESTIONS.length, PASSING=Math.ceil(TOTAL*0.80), KEY="khaemenes_science_u01_v1";
 let answers=new Array(TOTAL).fill(null), current=0;
 const $=(s,p=document)=>p.querySelector(s);
 function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}}
 function saveResult(score,domains){const state=load(),prior=state[FIELD]||{attempts:0,bestScore:0};const attempt=(prior.attempts||0)+1,bestScore=Math.max(prior.bestScore||0,score),passed=bestScore>=PASSING;state[FIELD]={passed,score,total:TOTAL,bestScore,bestPercent:Math.round(bestScore/TOTAL*100),attempts:attempt,lastCompletedAt:new Date().toISOString(),domainResults:domains};if(passed&&!prior.passed)state[FIELD].firstPassedAt=new Date().toISOString();else if(prior.firstPassedAt)state[FIELD].firstPassedAt=prior.firstPassedAt;state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));}
 function escape(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
 function render(){const q=QUESTIONS[current];$("#domainLabel").textContent=q.domain;$("#questionNumber").textContent=`Question ${current+1} of ${TOTAL}`;$("#questionPrompt").textContent=q.prompt;$("#options").innerHTML=q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[current]===i?"checked":""}><span>${escape(o)}</span></label>`).join("");$("#options").querySelectorAll("input").forEach(input=>input.addEventListener("change",e=>{answers[current]=Number(e.target.value);renderDots();updateSubmit();}));$("#previousButton").disabled=current===0;$("#nextButton").disabled=current===TOTAL-1;renderDots();}
 function renderDots(){$("#questionDots").innerHTML=QUESTIONS.map((_,i)=>`<button class="dot ${i===current?"current":""} ${answers[i]!==null?"answered":""}" type="button" data-i="${i}" aria-label="Question ${i+1}${answers[i]!==null?', answered':''}">${i+1}</button>`).join("");$("#questionDots").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{current=Number(b.dataset.i);render();}));}
 function updateSubmit(){$("#submitButton").disabled=answers.some(v=>v===null)}
 function submit(){if(answers.some(v=>v===null))return;const domains={};let score=0;QUESTIONS.forEach((q,i)=>{domains[q.domain]||={correct:0,total:0};domains[q.domain].total++;if(answers[i]===q.answer){score++;domains[q.domain].correct++;}});const passed=score>=PASSING;saveResult(score,domains);$("#assessment").hidden=true;$("#intro").hidden=true;$("#results").hidden=false;$("#score").textContent=`${score} / ${TOTAL}`;$("#resultTitle").textContent=passed?"Mastery threshold reached":"Mastery threshold not yet reached";$("#resultMessage").textContent=passed?`You reached the ${Math.round(PASSING/TOTAL*100)}% quiz threshold. Review every explanation, including correct items, before continuing to the remaining Unit 01 mastery evidence.`:`You answered ${score} of ${TOTAL} correctly. At least ${PASSING} of ${TOTAL} is required. Use the review to identify concepts, complete corrections, then begin a new attempt.`;$("#domainGrid").innerHTML=Object.entries(domains).map(([name,d])=>`<div class="domain-result"><strong>${d.correct} / ${d.total}</strong><span>${escape(name)}</span></div>`).join("");$("#reviewList").innerHTML=QUESTIONS.map((q,i)=>{const correct=answers[i]===q.answer;return `<article class="review-item ${correct?'correct':'incorrect'}"><strong>${i+1}. ${escape(q.prompt)}</strong><p>Your answer: ${escape(q.options[answers[i]])}</p><p>Correct answer: ${escape(q.options[q.answer])}</p><p>Concept review: ${escape(q.explanation)}</p></article>`;}).join("");window.scrollTo({top:0,behavior:"smooth"});}
 function start(){$("#intro").hidden=true;$("#results").hidden=true;$("#assessment").hidden=false;render();updateSubmit();}
 function retake(){answers=new Array(TOTAL).fill(null);current=0;$("#results").hidden=true;$("#assessment").hidden=false;render();updateSubmit();window.scrollTo({top:0,behavior:"smooth"});}
 document.addEventListener("DOMContentLoaded",()=>{$("#startButton").addEventListener("click",start);$("#previousButton").addEventListener("click",()=>{if(current>0){current--;render();}});$("#nextButton").addEventListener("click",()=>{if(current<TOTAL-1){current++;render();}});$("#submitButton").addEventListener("click",submit);$("#retakeButton").addEventListener("click",retake);$("#printResults").addEventListener("click",()=>window.print());});
})();